package com.jsirgalaxybase.ui2.terminal;

import java.util.List;

import com.jsirgalaxybase.ui2.component.ComponentUiDocument;
import com.jsirgalaxybase.ui2.component.StandardWidgets;
import com.jsirgalaxybase.ui2.component.UiActionHandler;
import com.jsirgalaxybase.ui2.core.UiContext;
import com.jsirgalaxybase.ui2.core.UiElement;
import com.jsirgalaxybase.ui2.geometry.Insets;
import com.jsirgalaxybase.ui2.geometry.UiSize;
import com.jsirgalaxybase.ui2.input.InputResult;
import com.jsirgalaxybase.ui2.input.UiEvent;
import com.jsirgalaxybase.ui2.input.UiInputHandler;
import com.jsirgalaxybase.ui2.input.UiInputNode;
import com.jsirgalaxybase.ui2.input.UiKeyCode;
import com.jsirgalaxybase.ui2.core.UiNode;
import com.jsirgalaxybase.ui2.geometry.UiRect;
import com.jsirgalaxybase.ui2.layout.LayoutKind;
import com.jsirgalaxybase.ui2.layout.LayoutSpec;

/** Production asset center layout shared by Minecraft and deterministic Java2D previews. */
public class AssetCenterVisualDocument extends ComponentUiDocument {
    private AssetCenterVisualModel model; private final TerminalActionPort shellActions;
    private final AssetCenterActionPort actions; private TerminalWindowProfile profile; private int mainWidth,width,height;
    public AssetCenterVisualDocument(AssetCenterVisualModel model,TerminalActionPort shellActions,AssetCenterActionPort actions,TerminalWindowProfile profile){super(StandardWidgets.create());if(model==null)throw new IllegalArgumentException("model is required");this.model=model;this.shellActions=shellActions==null?TerminalActionPort.NONE:shellActions;this.actions=actions==null?AssetCenterActionPort.NONE:actions;this.profile=profile==null?TerminalWindowProfile.STANDARD:profile;}
    public final void updateVisualModel(AssetCenterVisualModel value){if(value==null)throw new IllegalArgumentException("model is required");model=value;}
    public final void updateWindowProfile(TerminalWindowProfile value){profile=value==null?TerminalWindowProfile.STANDARD:value;}
    @Override public UiElement build(UiContext context){UiElement tabs=UiElement.type("Row").key("asset-tabs").child(tab("asset-storage-tab","存储管理",model.getTab()==AssetCenterVisualModel.Tab.STORAGE,AssetCenterVisualModel.Tab.STORAGE)).child(tab("asset-activity-tab","资产动态",model.getTab()==AssetCenterVisualModel.Tab.ACTIVITY,AssetCenterVisualModel.Tab.ACTIVITY)).build();UiElement body=model.getTab()==AssetCenterVisualModel.Tab.STORAGE?storage():activity();UiElement base=UiElement.type("Column").key("asset-base").child(tabs).child(body).build();UiElement.Builder page=UiElement.type("Stack").key("asset-page").child(base);if(model.isHelpOpen())page.child(UiElement.type("Dialog").key("asset-help").prop(StandardWidgets.TEXT,"银河资产中心").prop(StandardWidgets.DETAIL,"左侧管理 Base Vault 与背包；Cell 必须手动放入右侧 Bay。背包 Shift 点击优先进入 Vault。").build());return TerminalVisualShell.build(model.getShell(),page.build(),shellActions,"银河资产中心","assets");}
    private UiElement storage(){UiElement left=UiElement.type("Card").key("asset-left").child(UiElement.type("Row").key("asset-left-header").child(label("asset-vault-label","Base Vault · 27 格")).child(button("asset-sort","整理",new Runnable(){public void run(){actions.sortVault();}},true)).build()).child(slots("asset-vault","asset:vault",9,27)).child(label("asset-player-label","玩家背包")).child(slots("asset-player","asset:player",9,36)).build();UiElement.Builder right=UiElement.type("Card").key("asset-right").child(UiElement.type("Row").key("asset-bay-row").child(slots("asset-bay","asset:bay",1,1)).child(label("asset-bay-label",model.isCellPresent()?"Cell 已连接":"Bay：拖入 Cell")).build());if(!model.isCellPresent())right.child(UiElement.type("EmptyState").key("asset-cell-empty").prop(StandardWidgets.TEXT,"插入 Cell 后显示内容").build());else{right.child(label("asset-cell-facts",compact(model.getUsedBytes())+"/"+compact(model.getTotalBytes())+" B · "+model.getStoredTypes()+"/"+model.getTotalTypes()+" 类"));right.child(button("asset-deposit",model.isCursorOccupied()?"存入手持物品":"拿起物品后存入",new Runnable(){public void run(){actions.depositCursor();}},model.isCursorOccupied()));UiElement.Builder cells=UiElement.type("Root").key("asset-cell-cells");for(int i=0;i<20;i++){UiElement.Builder item=UiElement.type("ExternalItem").key("asset-cell-"+i);if(i<model.getCellItems().size()){final VisualItem visual=model.getCellItems().get(i);item.prop(StandardWidgets.EXTERNAL_ID,"asset:cell:"+i).prop(StandardWidgets.QUANTITY,compact(visual.getQuantity())).prop(StandardWidgets.ACTION,new UiActionHandler(){public InputResult handle(UiEvent event){actions.extract(visual.getId(),event.getButton()==1);return InputResult.CONSUMED;}});}cells.child(item.build());}right.child(UiElement.type("Stack").key("asset-cell-grid").child(cells.build()).build()).child(UiElement.type("Row").key("asset-pager").child(button("asset-prev","‹",new Runnable(){public void run(){actions.page(model.getPageIndex()-1);}},model.getPageIndex()>0)).child(label("asset-page-label",(model.getPageIndex()+1)+" / "+model.getTotalPages())).child(button("asset-next","›",new Runnable(){public void run(){actions.page(model.getPageIndex()+1);}},model.getPageIndex()+1<model.getTotalPages())).build());}return UiElement.type("Row").key("asset-storage").child(left).child(right.build()).build();}
    private UiElement activity(){UiElement.Builder card=UiElement.type("Card").key("asset-activity").child(label("asset-activity-title","系统资产业务动态"));List<AssetCenterVisualModel.Activity> rows=model.getActivities();if(rows.isEmpty())card.child(UiElement.type("EmptyState").key("asset-activity-empty").prop(StandardWidgets.TEXT,"暂无市场成交、交付、返还或恢复动态").build());else for(int i=0;i<rows.size();i++){AssetCenterVisualModel.Activity row=rows.get(i);UiElement.Builder line=UiElement.type("Row").key("asset-activity-row-"+i);if(row.getItem()!=null)line.child(UiElement.type("ExternalItem").key("asset-activity-item-"+i).prop(StandardWidgets.EXTERNAL_ID,"asset:activity:"+i).build());line.child(label("asset-activity-text-"+i,row.getLabel()+" · "+row.getDetail())).child(label("asset-activity-meta-"+i,row.getTime()));card.child(line.build());}return card.build();}
    @Override public LayoutSpec layout(UiElement root,UiSize viewport,UiContext context){width=viewport.getWidth();height=viewport.getHeight();TerminalVisualMetrics metrics=TerminalVisualMetrics.compute(viewport,profile);mainWidth=metrics.getMainWidth();boolean compact=metrics.getBounds().getHeight()<=220;LayoutSpec body=model.getTab()==AssetCenterVisualModel.Tab.STORAGE?storageLayout(compact):activityLayout();LayoutSpec base=LayoutSpec.of("asset-base",LayoutKind.COLUMN).flex(1F).gap(compact?2:4).child(LayoutSpec.of("asset-tabs",LayoutKind.ROW).preferred(0,compact?18:22).gap(4).child(LayoutSpec.of("asset-storage-tab",LayoutKind.LEAF).flex(1).build()).child(LayoutSpec.of("asset-activity-tab",LayoutKind.LEAF).flex(1).build()).build()).child(body).build();LayoutSpec.Builder page=LayoutSpec.of("asset-page",LayoutKind.STACK).flex(1F).child(base);if(model.isHelpOpen())page.child(LayoutSpec.of("asset-help",LayoutKind.LEAF).build());return TerminalVisualShell.layout(viewport,model.getShell(),page.build(),profile);}
    private LayoutSpec storageLayout(boolean compact){int leftWidth=Math.max(146,(TerminalVisualMetrics.compute(new UiSize(427,240),profile).getMainWidth()-4)*54/100);LayoutSpec left=LayoutSpec.of("asset-left",LayoutKind.COLUMN).preferred(leftWidth,0).padding(compact?Insets.ZERO:new Insets(2,2,2,2)).child(LayoutSpec.of("asset-left-header",LayoutKind.ROW).preferred(0,compact?12:16).child(LayoutSpec.of("asset-vault-label",LayoutKind.LEAF).flex(1).build()).child(LayoutSpec.of("asset-sort",LayoutKind.LEAF).preferred(38,compact?12:16).build()).build()).child(LayoutSpec.of("asset-vault",LayoutKind.LEAF).preferred(0,56).build()).child(LayoutSpec.of("asset-player-label",LayoutKind.LEAF).preferred(0,compact?10:14).build()).child(LayoutSpec.of("asset-player",LayoutKind.LEAF).preferred(0,74).build()).build();LayoutSpec.Builder right=LayoutSpec.of("asset-right",LayoutKind.COLUMN).flex(1).gap(2).padding(compact?Insets.ZERO:new Insets(2,2,2,2)).child(LayoutSpec.of("asset-bay-row",LayoutKind.ROW).preferred(0,20).gap(3).child(LayoutSpec.of("asset-bay",LayoutKind.LEAF).preferred(20,20).build()).child(LayoutSpec.of("asset-bay-label",LayoutKind.LEAF).flex(1).build()).build());if(!model.isCellPresent())right.child(LayoutSpec.of("asset-cell-empty",LayoutKind.LEAF).flex(1).build());else{right.child(LayoutSpec.of("asset-cell-facts",LayoutKind.LEAF).preferred(0,12).build()).child(LayoutSpec.of("asset-deposit",LayoutKind.LEAF).preferred(0,18).build());LayoutSpec.Builder cells=LayoutSpec.of("asset-cell-cells",LayoutKind.GRID).columns(5).gap(2);for(int i=0;i<20;i++)cells.child(LayoutSpec.of("asset-cell-"+i,LayoutKind.LEAF).build());right.child(LayoutSpec.of("asset-cell-grid",LayoutKind.STACK).flex(1).child(cells.build()).build()).child(LayoutSpec.of("asset-pager",LayoutKind.ROW).preferred(0,18).gap(3).child(LayoutSpec.of("asset-prev",LayoutKind.LEAF).preferred(24,18).build()).child(LayoutSpec.of("asset-page-label",LayoutKind.LEAF).flex(1).build()).child(LayoutSpec.of("asset-next",LayoutKind.LEAF).preferred(24,18).build()).build());}return LayoutSpec.of("asset-storage",LayoutKind.ROW).flex(1).gap(4).child(left).child(right.build()).build();}
    private LayoutSpec activityLayout(){LayoutSpec.Builder card=LayoutSpec.of("asset-activity",LayoutKind.COLUMN).flex(1).gap(2).padding(new Insets(5,5,5,5)).child(LayoutSpec.of("asset-activity-title",LayoutKind.LEAF).preferred(0,16).build());if(model.getActivities().isEmpty())card.child(LayoutSpec.of("asset-activity-empty",LayoutKind.LEAF).flex(1).build());else for(int i=0;i<model.getActivities().size();i++){AssetCenterVisualModel.Activity row=model.getActivities().get(i);LayoutSpec.Builder line=LayoutSpec.of("asset-activity-row-"+i,LayoutKind.ROW).preferred(0,18).gap(3);if(row.getItem()!=null)line.child(LayoutSpec.of("asset-activity-item-"+i,LayoutKind.LEAF).preferred(18,18).build());line.child(LayoutSpec.of("asset-activity-text-"+i,LayoutKind.LEAF).flex(2).build()).child(LayoutSpec.of("asset-activity-meta-"+i,LayoutKind.LEAF).flex(1).build());card.child(line.build());}return card.build();}
    @Override public UiInputNode modalInput(UiNode root,UiContext context){if(!model.isHelpOpen())return null;int dialogWidth=Math.min(230,Math.max(80,width-40)),dialogHeight=Math.min(90,Math.max(50,height-30));UiRect dialog=new UiRect((width-dialogWidth)/2,(height-dialogHeight)/2,dialogWidth,dialogHeight);UiInputNode modal=new UiInputNode("asset-help",new UiRect(0,0,width,height),false,new UiInputHandler(){@Override public InputResult handle(UiInputNode target,UiEvent event){if((event.getPhase()==UiEvent.Phase.TARGET&&event.getType()==UiEvent.Type.POINTER_DOWN)||(event.getType()==UiEvent.Type.KEY_DOWN&&event.getKeyCode()==UiKeyCode.ESCAPE)){actions.closeHelp();return InputResult.CONSUMED;}return InputResult.PASS;}});modal.add(new UiInputNode("asset-help-body",dialog,false,new UiInputHandler(){@Override public InputResult handle(UiInputNode target,UiEvent event){return event.getType()==UiEvent.Type.POINTER_DOWN?InputResult.CONSUMED:InputResult.PASS;}}));return modal;}
    private UiElement tab(String key,String text,boolean selected,final AssetCenterVisualModel.Tab tab){return UiElement.type("Tab").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.SELECTED,selected).prop(StandardWidgets.ACTION,new UiActionHandler(){public InputResult handle(UiEvent event){actions.selectTab(tab);return InputResult.CONSUMED;}}).build();}
    private static UiElement label(String key,String text){return UiElement.type("Label").key(key).prop(StandardWidgets.TEXT,text).build();}
    private static UiElement slots(String key,String id,int columns,int count){return UiElement.type("NativeSlotRegion").key(key).prop(StandardWidgets.EXTERNAL_ID,id).prop(StandardWidgets.COLUMNS,columns).prop(StandardWidgets.COUNT,count).build();}
    private static UiElement button(String key,String text,final Runnable run,boolean enabled){return UiElement.type("Button").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.ENABLED,enabled).prop(StandardWidgets.ACTION,new UiActionHandler(){public InputResult handle(UiEvent event){run.run();return InputResult.CONSUMED;}}).build();}
    public static String compact(long value){if(value<1000)return String.valueOf(value);if(value<1000000)return trim(value/1000D)+"K";if(value<1000000000)return trim(value/1000000D)+"M";return trim(value/1000000000D)+"G";}
    private static String trim(double value){return value>=100?String.format(java.util.Locale.ROOT,"%.0f",value):String.format(java.util.Locale.ROOT,"%.1f",value);}
}
