package com.jsirgalaxybase.ui2.terminal;

import java.util.List;

import com.jsirgalaxybase.ui2.component.ComponentUiDocument;
import com.jsirgalaxybase.ui2.component.StandardWidgets;
import com.jsirgalaxybase.ui2.core.UiContext;
import com.jsirgalaxybase.ui2.core.UiElement;
import com.jsirgalaxybase.ui2.core.UiNode;
import com.jsirgalaxybase.ui2.geometry.Insets;
import com.jsirgalaxybase.ui2.geometry.UiRect;
import com.jsirgalaxybase.ui2.geometry.UiSize;
import com.jsirgalaxybase.ui2.layout.LayoutKind;
import com.jsirgalaxybase.ui2.layout.LayoutSpec;
import com.jsirgalaxybase.ui2.render.DrawCommand;
import com.jsirgalaxybase.ui2.render.DrawList;
import com.jsirgalaxybase.ui2.render.UiLayer;

/** Headless-capable standard market catalog/detail document with native chart commands. */
public class MarketVisualDocument extends ComponentUiDocument {
    private MarketVisualModel model;private TerminalWindowProfile profile;
    public MarketVisualDocument(MarketVisualModel model,TerminalWindowProfile profile){super(StandardWidgets.create());if(model==null)throw new IllegalArgumentException("model is required");this.model=model;this.profile=profile==null?TerminalWindowProfile.STANDARD:profile;}
    public final void updateVisualModel(MarketVisualModel value){if(value==null)throw new IllegalArgumentException("model is required");model=value;}
    @Override public UiElement build(UiContext context){return TerminalVisualShell.build(model.getShell(),model.getView()==MarketVisualModel.View.DETAIL?detail():catalog(),TerminalActionPort.NONE,model.getView()==MarketVisualModel.View.DETAIL?"标准商品 · "+model.selected().getItem().getDisplayName():"标准商品市场","market");}
    private UiElement catalog(){UiElement.Builder grid=UiElement.type("Grid").key("market-grid");int count=Math.min(8,model.getProducts().size());for(int i=0;i<count;i++){MarketVisualModel.Product p=model.getProducts().get(i);grid.child(UiElement.type("Card").key("market-product-"+i).child(UiElement.type("ExternalItem").key("market-item-"+i).prop(StandardWidgets.EXTERNAL_ID,"market:item:"+i).build()).child(label("market-name-"+i,p.getItem().getDisplayName())).child(label("market-price-"+i,p.getLatest()+" GT · "+(p.getChange()>=0?"+":"")+p.getChange()+"%" )).build());}return UiElement.type("Column").key("market-catalog").child(UiElement.type("Row").key("market-tools").child(label("market-query","搜索商品名称…")).child(label("market-filter","筛选 · 全部")).child(label("market-sort","排序 · 默认")).build()).child(grid.build()).child(label("market-page","1 / 1 · "+model.getFreshness())).build();}
    private UiElement detail(){MarketVisualModel.Product p=model.selected();return UiElement.type("Column").key("market-detail").child(UiElement.type("Row").key("market-detail-head").child(label("market-back","‹ 商品目录")).child(label("market-fresh",model.getFreshness())).child(label("market-range",model.getRange())).build()).child(UiElement.type("Row").key("market-work").child(UiElement.type("Card").key("market-summary").child(UiElement.type("ExternalItem").key("market-detail-item").prop(StandardWidgets.EXTERNAL_ID,"market:detail:item").build()).child(label("market-detail-name",p.getItem().getDisplayName())).child(label("market-latest",p.getLatest()+" GT")).child(label("market-book","买一 101 ×128    最近 102    卖一 103 ×128")).child(label("market-stats","24h 量 "+p.getVolume()+" · 可用 320 · 锁定 0")).build()).child(UiElement.type("Card").key("market-chart-card").child(UiElement.type("Surface").key("market-chart").build()).build()).build()).build();}
    @Override public LayoutSpec layout(UiElement root,UiSize viewport,UiContext context){TerminalVisualMetrics metrics=TerminalVisualMetrics.compute(viewport,profile);int columns=metrics.getBounds().getWidth()>=560?4:metrics.getBounds().getWidth()>=400?3:2;boolean compact=metrics.getBounds().getHeight()<=220;LayoutSpec content;if(model.getView()==MarketVisualModel.View.CATALOG){LayoutSpec.Builder grid=LayoutSpec.of("market-grid",LayoutKind.GRID).columns(columns).flex(1).gap(3);for(int i=0;i<Math.min(8,model.getProducts().size());i++)grid.child(LayoutSpec.of("market-product-"+i,LayoutKind.COLUMN).padding(new Insets(2,2,2,2)).gap(1).child(LayoutSpec.of("market-item-"+i,LayoutKind.LEAF).preferred(compact?14:18,compact?14:18).build()).child(LayoutSpec.of("market-name-"+i,LayoutKind.LEAF).preferred(0,compact?9:10).build()).child(LayoutSpec.of("market-price-"+i,LayoutKind.LEAF).preferred(0,compact?9:10).build()).build());content=LayoutSpec.of("market-catalog",LayoutKind.COLUMN).flex(1).padding(new Insets(4,4,4,4)).gap(3).child(LayoutSpec.of("market-tools",LayoutKind.ROW).preferred(0,18).gap(3).child(LayoutSpec.of("market-query",LayoutKind.LEAF).flex(1).build()).child(LayoutSpec.of("market-filter",LayoutKind.LEAF).preferred(70,0).build()).child(LayoutSpec.of("market-sort",LayoutKind.LEAF).preferred(70,0).build()).build()).child(grid.build()).child(LayoutSpec.of("market-page",LayoutKind.LEAF).preferred(0,12).build()).build();}else{LayoutSpec summary=LayoutSpec.of("market-summary",LayoutKind.COLUMN).preferred(metrics.getMainWidth()*28/100,0).padding(new Insets(5,5,5,5)).gap(3).child(LayoutSpec.of("market-detail-item",LayoutKind.LEAF).preferred(28,28).build()).child(line("market-detail-name",14)).child(line("market-latest",14)).child(line("market-book",12)).child(line("market-stats",12)).build();content=LayoutSpec.of("market-detail",LayoutKind.COLUMN).flex(1).padding(new Insets(4,4,4,4)).gap(3).child(LayoutSpec.of("market-detail-head",LayoutKind.ROW).preferred(0,18).gap(3).child(LayoutSpec.of("market-back",LayoutKind.LEAF).preferred(68,0).build()).child(LayoutSpec.of("market-fresh",LayoutKind.LEAF).flex(1).build()).child(LayoutSpec.of("market-range",LayoutKind.LEAF).preferred(34,0).build()).build()).child(LayoutSpec.of("market-work",LayoutKind.ROW).flex(1).gap(3).child(summary).child(LayoutSpec.of("market-chart-card",LayoutKind.COLUMN).flex(1).padding(new Insets(4,4,4,4)).child(LayoutSpec.of("market-chart",LayoutKind.LEAF).flex(1).build()).build()).build()).build();}return TerminalVisualShell.layout(viewport,model.getShell(),content,profile);}
    @Override public DrawList paint(UiNode root,UiContext context){DrawList list=super.paint(root,context);if(model.getView()!=MarketVisualModel.View.DETAIL)return list;UiNode chart=find(root,"market-chart");if(chart==null)return list;UiRect bounds=chart.getBounds();List<MarketVisualModel.Point> points=model.selected().getPoints();if(points.isEmpty()){list.add(DrawCommand.text(UiLayer.NATIVE_OVERLAY,bounds,context.getTheme().color("textMuted"),"暂无成交"));return list;}long min=Long.MAX_VALUE,max=Long.MIN_VALUE,maxVolume=1;for(MarketVisualModel.Point p:points){min=Math.min(min,p.getValue());max=Math.max(max,p.getValue());maxVolume=Math.max(maxVolume,p.getVolume());}if(min==max){min--;max++;}StringBuilder line=new StringBuilder(),bars=new StringBuilder();int plotH=Math.max(1,bounds.getHeight()*3/4);for(int i=0;i<points.size();i++){int x=bounds.getX()+(points.size()==1?bounds.getWidth()/2:i*Math.max(1,bounds.getWidth()-1)/Math.max(1,points.size()-1));int y=bounds.getY()+(int)((max-points.get(i).getValue())*(plotH-1)/Math.max(1,max-min));if(line.length()>0)line.append(';');line.append(x).append(',').append(y);int bh=(int)(points.get(i).getVolume()*Math.max(1,bounds.getHeight()-plotH)/maxVolume);if(bars.length()>0)bars.append(';');bars.append(x).append(',').append(bounds.getBottom()-bh).append(',').append(2).append(',').append(bh);}if(points.size()==1){line.insert(0,bounds.getX()+","+line.substring(line.indexOf(",")+1)+";");line.append(';').append(bounds.getRight()-1).append(',').append(line.substring(line.lastIndexOf(",")+1));}list.add(DrawCommand.chartVolume(UiLayer.NATIVE_OVERLAY,bounds,0x8833AA66,bars.toString()));list.add(DrawCommand.chartLine(UiLayer.NATIVE_OVERLAY,bounds,context.getTheme().color("accent"),line.toString()));return list;}
    private static UiNode find(UiNode n,String key){if(n==null)return null;if(n.getElement().getKey()!=null&&key.equals(n.getElement().getKey().getValue()))return n;for(UiNode c:n.getChildren()){UiNode found=find(c,key);if(found!=null)return found;}return null;}
    private static LayoutSpec line(String key,int height){return LayoutSpec.of(key,LayoutKind.LEAF).preferred(0,height).build();}
    private static UiElement label(String key,String text){return UiElement.type("Label").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.MAX_LINES,1).build();}
}
