package com.jsirgalaxybase.ui2.terminal;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.LinkedHashMap;

public final class QuestManagementVisualModel {
    private final TerminalVisualModel shell;private final String query,lifecycle,message;private final int page,pageSize;private final long total;private final List<Definition> definitions;private final Detail detail;private final List<ElementType> taskTypes,rewardTypes;private final List<Migration> migrations;
    public QuestManagementVisualModel(TerminalVisualModel shell,String query,String lifecycle,String message,int page,int pageSize,long total,List<Definition> definitions){this(shell,query,lifecycle,message,page,pageSize,total,definitions,null);}
    public QuestManagementVisualModel(TerminalVisualModel shell,String query,String lifecycle,String message,int page,int pageSize,long total,List<Definition> definitions,Detail detail){this(shell,query,lifecycle,message,page,pageSize,total,definitions,detail,Collections.<ElementType>emptyList(),Collections.<ElementType>emptyList());}
    public QuestManagementVisualModel(TerminalVisualModel shell,String query,String lifecycle,String message,int page,int pageSize,long total,List<Definition> definitions,Detail detail,List<ElementType> taskTypes,List<ElementType> rewardTypes){this(shell,query,lifecycle,message,page,pageSize,total,definitions,detail,taskTypes,rewardTypes,Collections.<Migration>emptyList());}
    public QuestManagementVisualModel(TerminalVisualModel shell,String query,String lifecycle,String message,int page,int pageSize,long total,List<Definition> definitions,Detail detail,List<ElementType> taskTypes,List<ElementType> rewardTypes,List<Migration> migrations){if(shell==null)throw new IllegalArgumentException("shell is required");this.shell=shell;this.query=text(query);this.lifecycle=text(lifecycle);this.message=text(message);this.page=Math.max(0,page);this.pageSize=Math.max(1,pageSize);this.total=Math.max(0,total);this.definitions=definitions==null?Collections.<Definition>emptyList():Collections.unmodifiableList(new ArrayList<Definition>(definitions));this.detail=detail;this.taskTypes=copy(taskTypes);this.rewardTypes=copy(rewardTypes);this.migrations=copy(migrations);}
    public TerminalVisualModel getShell(){return shell;}public String getQuery(){return query;}public String getLifecycle(){return lifecycle;}public String getMessage(){return message;}public int getPage(){return page;}public int getPageSize(){return pageSize;}public long getTotal(){return total;}public List<Definition> getDefinitions(){return definitions;}public Detail getDetail(){return detail;}public List<ElementType> getTaskTypes(){return taskTypes;}public List<ElementType> getRewardTypes(){return rewardTypes;}public List<Migration> getMigrations(){return migrations;}public int getPages(){return Math.max(1,(int)Math.min(Integer.MAX_VALUE,(total+pageSize-1L)/pageSize));}
    private static String text(String value){return value==null?"":value;}
    public static final class Definition{private final String id,name,lifecycle,hash;private final int version,tasks,rewards;private final long publishedAt;public Definition(String id,int version,String name,String lifecycle,String hash,long publishedAt,int tasks,int rewards){this.id=text(id);this.version=Math.max(1,version);this.name=text(name);this.lifecycle=text(lifecycle);this.hash=text(hash);this.publishedAt=Math.max(0,publishedAt);this.tasks=Math.max(0,tasks);this.rewards=Math.max(0,rewards);}public String getId(){return id;}public int getVersion(){return version;}public String getName(){return name;}public String getLifecycle(){return lifecycle;}public String getHash(){return hash;}public long getPublishedAt(){return publishedAt;}public int getTasks(){return tasks;}public int getRewards(){return rewards;}}
    public static final class Detail{private final Definition summary;private final String description,prerequisiteLogic,taskLogic;private final List<String> prerequisites;private final List<Element> tasks,rewards;private final Map<String,String> options;public Detail(Definition summary,String description,String prerequisiteLogic,String taskLogic,List<String> prerequisites,List<Element> tasks,List<Element> rewards,Map<String,String> options){this.summary=summary;this.description=text(description);this.prerequisiteLogic=text(prerequisiteLogic);this.taskLogic=text(taskLogic);this.prerequisites=copy(prerequisites);this.tasks=copy(tasks);this.rewards=copy(rewards);this.options=options==null?Collections.<String,String>emptyMap():Collections.unmodifiableMap(new LinkedHashMap<String,String>(options));}public Definition getSummary(){return summary;}public String getDescription(){return description;}public String getPrerequisiteLogic(){return prerequisiteLogic;}public String getTaskLogic(){return taskLogic;}public List<String> getPrerequisites(){return prerequisites;}public List<Element> getTasks(){return tasks;}public List<Element> getRewards(){return rewards;}public Map<String,String> getOptions(){return options;}}
    public static final class Element{private final String key,typeId;private final boolean optional;private final Map<String,String> parameters;public Element(String key,String typeId,boolean optional,Map<String,String> parameters){this.key=text(key);this.typeId=text(typeId);this.optional=optional;this.parameters=parameters==null?Collections.<String,String>emptyMap():Collections.unmodifiableMap(new LinkedHashMap<String,String>(parameters));}public String getKey(){return key;}public String getTypeId(){return typeId;}public boolean isOptional(){return optional;}public Map<String,String> getParameters(){return parameters;}}
    public static final class ElementType{private final String id,name,kind;private final List<Field> fields;public ElementType(String id,String name,String kind,List<Field> fields){this.id=text(id);this.name=text(name);this.kind=text(kind);this.fields=copy(fields);}public String getId(){return id;}public String getName(){return name;}public String getKind(){return kind;}public List<Field> getFields(){return fields;}}
    public static final class Field{private final String key,label,type;private final boolean required;private final Long minimum,maximum;private final List<String> options;public Field(String key,String label,String type,boolean required,Long minimum,Long maximum,List<String> options){this.key=text(key);this.label=text(label);this.type=text(type);this.required=required;this.minimum=minimum;this.maximum=maximum;this.options=copy(options);}public String getKey(){return key;}public String getLabel(){return label;}public String getType(){return type;}public boolean isRequired(){return required;}public Long getMinimum(){return minimum;}public Long getMaximum(){return maximum;}public List<String> getOptions(){return options;}}
    public static final class Migration{private final String batchId,sourceHash,status,diagnostic;private final long appliedAt;private final int created,versioned,unchanged,errorCount,warningCount;public Migration(String batchId,String sourceHash,String status,long appliedAt,int created,int versioned,int unchanged,int errorCount,int warningCount,String diagnostic){this.batchId=text(batchId);this.sourceHash=text(sourceHash);this.status=text(status);this.appliedAt=Math.max(0,appliedAt);this.created=Math.max(0,created);this.versioned=Math.max(0,versioned);this.unchanged=Math.max(0,unchanged);this.errorCount=Math.max(0,errorCount);this.warningCount=Math.max(0,warningCount);this.diagnostic=text(diagnostic);}public String getBatchId(){return batchId;}public String getSourceHash(){return sourceHash;}public String getStatus(){return status;}public long getAppliedAt(){return appliedAt;}public int getCreated(){return created;}public int getVersioned(){return versioned;}public int getUnchanged(){return unchanged;}public int getErrorCount(){return errorCount;}public int getWarningCount(){return warningCount;}public String getDiagnostic(){return diagnostic;}}
    private static <T> List<T> copy(List<T> values){return values==null?Collections.<T>emptyList():Collections.unmodifiableList(new ArrayList<T>(values));}
}
