package com.jsirgalaxybase.ui2.terminal;

import com.jsirgalaxybase.ui2.component.ComponentUiDocument;
import com.jsirgalaxybase.ui2.component.StandardWidgets;
import com.jsirgalaxybase.ui2.component.UiActionHandler;
import com.jsirgalaxybase.ui2.core.UiContext;
import com.jsirgalaxybase.ui2.core.UiElement;
import com.jsirgalaxybase.ui2.core.UiNode;
import com.jsirgalaxybase.ui2.geometry.Insets;
import com.jsirgalaxybase.ui2.geometry.UiRect;
import com.jsirgalaxybase.ui2.geometry.UiSize;
import com.jsirgalaxybase.ui2.input.InputResult;
import com.jsirgalaxybase.ui2.input.UiEvent;
import com.jsirgalaxybase.ui2.input.UiInputHandler;
import com.jsirgalaxybase.ui2.input.UiInputNode;
import com.jsirgalaxybase.ui2.input.UiKeyCode;
import com.jsirgalaxybase.ui2.layout.LayoutKind;
import com.jsirgalaxybase.ui2.layout.LayoutSpec;

/** Actual production settings document backed by a platform-neutral state port. */
public class TerminalSettingsVisualDocument extends ComponentUiDocument {
    private final TerminalSettingsPort settings;private final TerminalActionPort shellActions;private int width,height;
    public TerminalSettingsVisualDocument(TerminalSettingsPort settings,TerminalActionPort shellActions){super(StandardWidgets.create());if(settings==null)throw new IllegalArgumentException("settings are required");this.settings=settings;this.shellActions=shellActions==null?TerminalActionPort.NONE:shellActions;}
    public final void openVisualHelp(){settings.openHelp();}
    @Override public UiElement build(UiContext context){final TerminalSettingsVisualModel model=settings.current();UiElement.Builder themes=UiElement.type("Row").key("settings-theme-row");for(final TerminalSettingsVisualModel.ThemeChoice theme:model.getThemes())themes.child(choice("settings-theme-"+theme.getId(),theme.getLabel(),model.getThemeId().equals(theme.getId()),new Runnable(){@Override public void run(){settings.selectTheme(theme.getId());}}));UiElement windows=UiElement.type("Row").key("settings-window-row").child(window("COMPACT","小窗",model,TerminalWindowProfile.COMPACT)).child(window("STANDARD","标准",model,TerminalWindowProfile.STANDARD)).child(window("LARGE","宽大",model,TerminalWindowProfile.LARGE)).build();UiElement controls=UiElement.type("Row").key("settings-controls").child(choice("settings-motion",model.isReducedMotion()?"减少动画：开":"减少动画：关",model.isReducedMotion(),new Runnable(){@Override public void run(){settings.toggleMotion();}})).child(choice("settings-reset","恢复默认",false,new Runnable(){@Override public void run(){settings.reset();}})).build();UiElement body=UiElement.type("Column").key("settings-base").child(label("settings-title","终端设置","section",true)).child(label("settings-theme-label","主题包 · 仅影响你的客户端","caption",false)).child(themes.build()).child(label("settings-font-label","字体跟随 Minecraft / 资源包 · 字号由终端固定","caption",false)).child(label("settings-window-label","终端窗口尺寸","caption",false)).child(windows).child(controls).build();UiElement.Builder page=UiElement.type("Stack").key("settings-page").child(body);if(model.isHelpOpen())page.child(UiElement.type("Dialog").key("settings-help").prop(StandardWidgets.TEXT,"终端外观设置").prop(StandardWidgets.DETAIL,"主题和窗口尺寸只保存在本机。文字始终使用 Minecraft 当前字体并跟随资源包；字号和原生物品槽尺寸由终端固定。").build());return TerminalVisualShell.build(model.getShell(),page.build(),shellActions,"银河终端设置",TerminalVisualShell.SETTINGS_PAGE_ID);}
    @Override public LayoutSpec layout(UiElement root,UiSize viewport,UiContext context){width=viewport.getWidth();height=viewport.getHeight();TerminalSettingsVisualModel model=settings.current();boolean compact=TerminalVisualMetrics.compute(viewport,model.getWindowProfile()).getBounds().getHeight()<=220;int row=compact?18:22,label=compact?10:12;LayoutSpec.Builder themeRow=LayoutSpec.of("settings-theme-row",LayoutKind.ROW).preferred(0,row).gap(4);for(TerminalSettingsVisualModel.ThemeChoice theme:model.getThemes())themeRow.child(LayoutSpec.of("settings-theme-"+theme.getId(),LayoutKind.LEAF).flex(1F).build());LayoutSpec windows=LayoutSpec.of("settings-window-row",LayoutKind.ROW).preferred(0,row).gap(4).child(LayoutSpec.of("settings-window-COMPACT",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("settings-window-STANDARD",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("settings-window-LARGE",LayoutKind.LEAF).flex(1F).build()).build();LayoutSpec base=LayoutSpec.of("settings-base",LayoutKind.COLUMN).padding(new Insets(5,6,5,6)).gap(compact?1:3).child(LayoutSpec.of("settings-title",LayoutKind.LEAF).preferred(0,16).build()).child(LayoutSpec.of("settings-theme-label",LayoutKind.LEAF).preferred(0,label).build()).child(themeRow.build()).child(LayoutSpec.of("settings-font-label",LayoutKind.LEAF).preferred(0,label).build()).child(LayoutSpec.of("settings-window-label",LayoutKind.LEAF).preferred(0,label).build()).child(windows).child(LayoutSpec.of("settings-controls",LayoutKind.ROW).preferred(0,row).gap(4).child(LayoutSpec.of("settings-motion",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("settings-reset",LayoutKind.LEAF).flex(1F).build()).build()).build();LayoutSpec.Builder page=LayoutSpec.of("settings-page",LayoutKind.STACK).flex(1F).child(base);if(model.isHelpOpen())page.child(LayoutSpec.of("settings-help",LayoutKind.LEAF).build());return TerminalVisualShell.layout(viewport,model.getShell(),page.build(),model.getWindowProfile());}
    @Override public UiInputNode modalInput(UiNode root,UiContext context){if(!settings.current().isHelpOpen())return null;return new UiInputNode("settings-help",new UiRect(0,0,width,height),false,new UiInputHandler(){@Override public InputResult handle(UiInputNode target,UiEvent event){if((event.getPhase()==UiEvent.Phase.TARGET&&event.getType()==UiEvent.Type.POINTER_DOWN)||(event.getType()==UiEvent.Type.KEY_DOWN&&event.getKeyCode()==UiKeyCode.ESCAPE)){settings.closeHelp();return InputResult.CONSUMED;}return InputResult.PASS;}});}
    private UiElement window(String key,String label,TerminalSettingsVisualModel model,final TerminalWindowProfile profile){return choice("settings-window-"+key,label,model.getWindowProfile()==profile,new Runnable(){@Override public void run(){settings.selectWindow(profile);}});}
    private static UiElement choice(String key,String text,boolean selected,final Runnable action){return UiElement.type("Button").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.SELECTED,selected).prop(StandardWidgets.ACTION,new UiActionHandler(){@Override public InputResult handle(UiEvent event){action.run();return InputResult.CONSUMED;}}).build();}
    private static UiElement label(String key,String text,String role,boolean bold){return UiElement.type("Label").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.TEXT_ROLE,role).prop(StandardWidgets.BOLD,bold).build();}
}
