package com.jsirgalaxybase.quest.bqimport;

import static org.junit.Assert.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import org.junit.*;
import com.jsirgalaxybase.quest.postgres.*;

public class BqMigrationDatabaseIntegrationTest {
    private DriverManagerQuestDataSource root,scoped; private String schema;
    @Before public void setUp() throws Exception {String user=System.getenv("POSTGRES_USER"),password=System.getenv("POSTGRES_PASSWORD"),database=System.getenv("POSTGRES_DB"),host=System.getenv("POSTGRES_HOST");Assume.assumeTrue(user!=null&&password!=null&&database!=null);if(host==null||host.isEmpty())host="galaxy-base";Class.forName("org.postgresql.Driver");String url="jdbc:postgresql://"+host+":5432/"+database;root=new DriverManagerQuestDataSource(url,user,password);schema="bq_migration_it_"+UUID.randomUUID().toString().replace("-","");try(Connection connection=root.getConnection();Statement statement=connection.createStatement()){statement.execute("CREATE SCHEMA \""+schema+"\"");}catch(SQLException unavailable){schema=null;Assume.assumeNoException(unavailable);}scoped=new DriverManagerQuestDataSource(url+"?currentSchema="+schema,user,password);try(Connection connection=scoped.getConnection();Statement statement=connection.createStatement()){statement.execute(ddl());}}
    @After public void tearDown() throws Exception {if(root!=null&&schema!=null)try(Connection connection=root.getConnection();Statement statement=connection.createStatement()){statement.execute("DROP SCHEMA IF EXISTS \""+schema+"\" CASCADE");}}
    @Test public void dryRunWritesNothingApplyIsIdempotentAndRollbackRetiresBatch() throws Exception {BqMigrationManifest manifest=new BqMigrationPlanner().plan(fixture());JdbcQuestConnectionManager manager=new JdbcQuestConnectionManager(scoped);BqMigrationDatabaseService service=new BqMigrationDatabaseService(new JdbcQuestTransaction(manager),new JdbcQuestDefinitionRepository(manager),new JdbcQuestChapterRepository(manager),new JdbcQuestContentMigrationRepository(manager));
        BqMigrationDryRun preview=service.dryRun(manifest);assertTrue(preview.isApplicable());assertEquals(2,preview.count(QuestContentMigrationItem.Action.CREATED));assertEquals(0,count("galaxy_quest_content_migration_batch"));QuestContentMigrationBatch staged=service.stage(manifest);assertEquals(QuestContentMigrationBatch.Status.PREVIEW,staged.getStatus());assertEquals(1,count("galaxy_quest_content_migration_batch"));assertEquals(0,countPublished("galaxy_quest_definition"));assertEquals(staged.getBatchId(),service.stage(manifest).getBatchId());
        QuestContentMigrationBatch first=service.apply(manifest,1000L);assertEquals(QuestContentMigrationBatch.Status.APPLIED,first.getStatus());assertEquals(1,count("galaxy_quest_content_migration_batch"));assertEquals(1,countPublished("galaxy_quest_definition"));assertEquals(1,countPublished("galaxy_quest_chapter_definition"));
        com.jsirgalaxybase.quest.core.QuestCenterPage center=new JdbcQuestCenterQuery(manager).loadPageForPlayer(UUID.randomUUID(),com.jsirgalaxybase.quest.core.QuestCenterPageRequest.initial());assertEquals(1,center.getChapters().size());assertEquals(1,center.getQuests().size());assertEquals("Q",center.getQuests().get(0).getDefinition().getName());
        QuestContentMigrationBatch second=service.apply(manifest,2000L);assertEquals(first.getBatchId(),second.getBatchId());assertEquals(1,count("galaxy_quest_content_migration_batch"));assertEquals(1,count("galaxy_quest_definition"));
        service.rollback(first.getBatchId());assertEquals(0,countPublished("galaxy_quest_definition"));assertEquals(0,countPublished("galaxy_quest_chapter_definition"));assertEquals(0,count("galaxy_quest_chapter_catalog"));assertEquals("ROLLED_BACK",status(first.getBatchId()));
        service.rollback(first.getBatchId());assertEquals("ROLLED_BACK",status(first.getBatchId()));
    }
    @Test public void failedApplyRollsBackEveryMigrationWrite() throws Exception {BqMigrationManifest manifest=new BqMigrationPlanner().plan(fixture());JdbcQuestConnectionManager manager=new JdbcQuestConnectionManager(scoped);JdbcQuestTransaction transaction=new JdbcQuestTransaction(manager);JdbcQuestDefinitionRepository definitions=new JdbcQuestDefinitionRepository(manager);BqMigrationDatabaseService service=new BqMigrationDatabaseService(transaction,definitions,new JdbcQuestChapterRepository(manager),new JdbcQuestContentMigrationRepository(manager));transaction.inTransaction(()->{definitions.createDraft(manifest.getQuests().get(0).getDefinition());return null;});try{service.apply(manifest,1L);fail("expected version conflict");}catch(com.jsirgalaxybase.quest.core.QuestDefinitionConflictException expected){}assertEquals(0,count("galaxy_quest_content_migration_batch"));assertEquals(1,count("galaxy_quest_definition"));assertEquals(0,count("galaxy_quest_chapter_definition"));}
    @Test public void changedContentCreatesControlledVersionAndProtectsEarlierRollback() throws Exception {Path firstSource=fixture();BqMigrationManifest first=new BqMigrationPlanner().plan(firstSource);JdbcQuestConnectionManager manager=new JdbcQuestConnectionManager(scoped);BqMigrationDatabaseService service=new BqMigrationDatabaseService(new JdbcQuestTransaction(manager),new JdbcQuestDefinitionRepository(manager),new JdbcQuestChapterRepository(manager),new JdbcQuestContentMigrationRepository(manager));service.apply(first,1L);Path quest=firstSource.resolve("Quests/line/q.json");String changed=new String(Files.readAllBytes(quest),StandardCharsets.UTF_8).replace("\"Q\"","\"Q2\"");Files.write(quest,changed.getBytes(StandardCharsets.UTF_8));BqMigrationManifest second=new BqMigrationPlanner().plan(firstSource);QuestContentMigrationBatch applied=service.apply(second,2L);QuestContentMigrationItem questItem=null;for(QuestContentMigrationItem item:applied.getItems())if(item.getKind()==QuestContentMigrationItem.Kind.QUEST)questItem=item;assertNotNull(questItem);assertEquals(2,questItem.getVersion());assertEquals(QuestContentMigrationItem.Action.VERSIONED,questItem.getAction());try{service.rollback(first.getBatchId());fail("later version must protect earlier batch");}catch(IllegalStateException expected){assertTrue(expected.getMessage().contains("later quest version"));}service.rollback(second.getBatchId());assertEquals("Q",new JdbcQuestDefinitionRepository(manager).findPublished(questItem.getId()).get().getDefinition().getName());service.rollback(first.getBatchId());assertEquals(0,countPublished("galaxy_quest_definition"));}
    @Test public void blockedPreviewIsVisibleButCannotApplyOrRollback() throws Exception {Path source=fixture();Path quest=source.resolve("Quests/line/q.json");String invalid=new String(Files.readAllBytes(quest),StandardCharsets.UTF_8).replace("bq_standard:checkbox","addon:unknown");Files.write(quest,invalid.getBytes(StandardCharsets.UTF_8));BqMigrationManifest manifest=new BqMigrationPlanner().plan(source);assertFalse(manifest.isApplicable());JdbcQuestConnectionManager manager=new JdbcQuestConnectionManager(scoped);BqMigrationDatabaseService service=new BqMigrationDatabaseService(new JdbcQuestTransaction(manager),new JdbcQuestDefinitionRepository(manager),new JdbcQuestChapterRepository(manager),new JdbcQuestContentMigrationRepository(manager));QuestContentMigrationBatch staged=service.stage(manifest);assertEquals(QuestContentMigrationBatch.Status.BLOCKED,staged.getStatus());assertTrue(staged.getErrorCount()>0);assertEquals(0,countPublished("galaxy_quest_definition"));try{service.apply(manifest,1L);fail("blocked manifest must not apply");}catch(IllegalArgumentException expected){}try{service.rollback(staged.getBatchId());fail("blocked preview must not roll back");}catch(IllegalStateException expected){}}
    @Test public void importedContentPreservesChapterPrerequisiteGoalRewardAndPlayerBrowse() throws Exception {BqMigrationManifest manifest=new BqMigrationPlanner().plan(richFixture());assertTrue(manifest.toText(),manifest.isApplicable());JdbcQuestConnectionManager manager=new JdbcQuestConnectionManager(scoped);JdbcQuestDefinitionRepository definitions=new JdbcQuestDefinitionRepository(manager);JdbcQuestChapterRepository chapters=new JdbcQuestChapterRepository(manager);BqMigrationDatabaseService service=new BqMigrationDatabaseService(new JdbcQuestTransaction(manager),definitions,chapters,new JdbcQuestContentMigrationRepository(manager));service.apply(manifest,1L);com.jsirgalaxybase.quest.core.StoredQuestDefinition second=definitions.findPublished(new UUID(0L,8L)).get();assertEquals("进阶钢材",second.getDefinition().getName());assertTrue(second.getDefinition().getPrerequisites().contains(new UUID(0L,7L)));assertEquals("bq_standard:retrieval",second.getDefinition().getTasks().get(0).getTypeId());assertEquals("64",second.getDefinition().getTasks().get(0).getParameters().get("target"));assertEquals("bq_standard:item",second.getDefinition().getRewards().get(0).getTypeId());com.jsirgalaxybase.quest.core.StoredQuestChapter chapter=chapters.findPublished(new UUID(0L,1L)).get();assertEquals(2,chapter.getDefinition().getEntries().size());assertTrue(chapter.getDefinition().getIconReference().contains("minecraft:book"));assertEquals("base:textures/gui/quests.png",chapter.getDefinition().getBackgroundReference());com.jsirgalaxybase.quest.core.QuestCenterPage center=new JdbcQuestCenterQuery(manager).loadPageForPlayer(UUID.randomUUID(),com.jsirgalaxybase.quest.core.QuestCenterPageRequest.initial());assertEquals(1,center.getChapters().size());assertEquals(2,center.getQuests().size());}
    private Path fixture() throws Exception {Path root=Files.createTempDirectory("bq-db-plan");Path quests=Files.createDirectories(root.resolve("Quests/line"));Files.write(quests.resolve("q.json"),("{\"questIDHigh:4\":0,\"questIDLow:4\":7,\"properties:10\":{\"betterquesting:10\":{\"name:8\":\"Q\"}},\"tasks:9\":{\"0:10\":{\"index:3\":0,\"taskID:8\":\"bq_standard:checkbox\"}},\"rewards:9\":{}}").getBytes(StandardCharsets.UTF_8));Files.write(root.resolve("QuestLinesOrder.txt"),"AAAAAAAAAAAAAAAAAAAAAQ==: Main\n".getBytes(StandardCharsets.UTF_8));Path line=Files.createDirectories(root.resolve("QuestLines/Main-AAAAAAAAAAAAAAAAAAAAAQ=="));Files.write(line.resolve("q.json"),"{\"questIDHigh:4\":0,\"questIDLow:4\":7,\"sizeX:3\":24,\"sizeY:3\":24,\"x:3\":0,\"y:3\":0}".getBytes(StandardCharsets.UTF_8));return root;}
    private Path richFixture()throws Exception{Path root=Files.createTempDirectory("bq-rich-plan");Path quests=Files.createDirectories(root.resolve("Quests/line"));Files.write(quests.resolve("first.json"),"{\"questIDHigh:4\":0,\"questIDLow:4\":7,\"properties:10\":{\"betterquesting:10\":{\"name:8\":\"基础钢材\"}},\"preRequisites:9\":{},\"tasks:9\":{\"0:10\":{\"index:3\":0,\"taskID:8\":\"bq_standard:checkbox\"}},\"rewards:9\":{}}".getBytes(StandardCharsets.UTF_8));Files.write(quests.resolve("second.json"),"{\"questIDHigh:4\":0,\"questIDLow:4\":8,\"properties:10\":{\"betterquesting:10\":{\"name:8\":\"进阶钢材\",\"desc:8\":\"提交一组钢锭\"}},\"preRequisites:9\":{\"0:10\":{\"questIDHigh:4\":0,\"questIDLow:4\":7}},\"tasks:9\":{\"0:10\":{\"index:3\":0,\"taskID:8\":\"bq_standard:retrieval\",\"requiredItems:9\":{\"0:10\":{\"id:8\":\"minecraft:iron_ingot\",\"Damage:2\":0,\"Count:3\":64}}}},\"rewards:9\":{\"0:10\":{\"index:3\":0,\"rewardID:8\":\"bq_standard:item\",\"rewards:9\":{\"0:10\":{\"id:8\":\"minecraft:gold_ingot\",\"Damage:2\":0,\"Count:3\":2}}}}}".getBytes(StandardCharsets.UTF_8));Files.write(root.resolve("QuestLinesOrder.txt"),"AAAAAAAAAAAAAAAAAAAAAQ==: Main\n".getBytes(StandardCharsets.UTF_8));Path line=Files.createDirectories(root.resolve("QuestLines/Main-AAAAAAAAAAAAAAAAAAAAAQ=="));Files.write(line.resolve("QuestLine.json"),"{\"questLineIDHigh:4\":0,\"questLineIDLow:4\":1,\"properties:10\":{\"betterquesting:10\":{\"name:8\":\"钢铁时代\",\"icon:10\":{\"id:8\":\"minecraft:book\"},\"bg_image:8\":\"base:textures/gui/quests.png\"}}}".getBytes(StandardCharsets.UTF_8));Files.write(line.resolve("first.json"),"{\"questIDHigh:4\":0,\"questIDLow:4\":7,\"sizeX:3\":24,\"sizeY:3\":24,\"x:3\":0,\"y:3\":0}".getBytes(StandardCharsets.UTF_8));Files.write(line.resolve("second.json"),"{\"questIDHigh:4\":0,\"questIDLow:4\":8,\"sizeX:3\":24,\"sizeY:3\":24,\"x:3\":32,\"y:3\":0}".getBytes(StandardCharsets.UTF_8));return root;}
    private long count(String table)throws Exception{try(Connection c=scoped.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT COUNT(*) FROM "+table)){r.next();return r.getLong(1);}}
    private long countPublished(String table)throws Exception{try(Connection c=scoped.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT COUNT(*) FROM "+table+" WHERE lifecycle='PUBLISHED'")){r.next();return r.getLong(1);}}
    private String status(String id)throws Exception{try(Connection c=scoped.getConnection();PreparedStatement s=c.prepareStatement("SELECT status FROM galaxy_quest_content_migration_batch WHERE batch_id=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){r.next();return r.getString(1);}}}
    private static String ddl()throws Exception{InputStream input=BqMigrationDatabaseIntegrationTest.class.getResourceAsStream("/com/jsirgalaxybase/quest/postgres/quest-postgresql-ddl.sql");assertNotNull(input);try(InputStream in=input;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];for(int read;(read=in.read(buffer))>=0;)out.write(buffer,0,read);return new String(out.toByteArray(),StandardCharsets.UTF_8);}}
}
