package com.jsirgalaxybase.quest.bqimport;
import java.nio.file.Paths;import com.jsirgalaxybase.quest.postgres.*;
/** Explicit offline entrypoint. Mutations require an isolated-environment confirmation token. */
public final class BqMigrationMain {
 private BqMigrationMain(){}
 public static void main(String[] args)throws Exception{if(args.length<2)throw new IllegalArgumentException("Usage: BqMigrationMain <plan|dry-run|preview|apply|rollback> <DefaultQuests|batch-id>");String command=args[0];if("plan".equals(command)){BqMigrationManifest manifest=new BqMigrationPlanner().plan(Paths.get(args[1]));System.out.print(manifest.toText());System.out.print(compatibility(manifest));return;}BqMigrationDatabaseService service=service();if("rollback".equals(command)){confirm();service.rollback(args[1]);System.out.println("rolledBack="+args[1]);return;}BqMigrationManifest manifest=new BqMigrationPlanner().plan(Paths.get(args[1]));BqMigrationDryRun preview=service.dryRun(manifest);System.out.print(manifest.toText());System.out.print(compatibility(manifest));System.out.print(preview.toText());if("dry-run".equals(command))return;if("preview".equals(command)){confirm();System.out.println("status="+service.stage(manifest).getStatus());return;}if(!"apply".equals(command))throw new IllegalArgumentException("unknown command: "+command);confirm();QuestContentMigrationBatch batch=service.apply(manifest,System.currentTimeMillis());System.out.println("status="+batch.getStatus());}
 private static String compatibility(BqMigrationManifest manifest){return BqCompatibilityReport.create(manifest).toText();}
 private static BqMigrationDatabaseService service(){String url=required("BQ_MIGRATION_JDBC_URL"),user=required("BQ_MIGRATION_DB_USER"),password=required("BQ_MIGRATION_DB_PASSWORD");JdbcQuestConnectionManager manager=new JdbcQuestConnectionManager(new DriverManagerQuestDataSource(url,user,password));return new BqMigrationDatabaseService(new JdbcQuestTransaction(manager),new JdbcQuestDefinitionRepository(manager),new JdbcQuestChapterRepository(manager),new JdbcQuestContentMigrationRepository(manager));}
 private static void confirm(){if(!"ISOLATED_ONLY".equals(System.getenv("BQ_MIGRATION_WRITE_CONFIRM")))throw new IllegalStateException("preview/apply/rollback requires BQ_MIGRATION_WRITE_CONFIRM=ISOLATED_ONLY");}
 private static String required(String name){String value=System.getenv(name);if(value==null||value.isEmpty())throw new IllegalArgumentException(name+" is required");return value;}
}
