package com.jsirgalaxybase.terminal.client.ui2;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import com.jsirgalaxybase.terminal.TerminalActionType;
import com.jsirgalaxybase.terminal.TerminalQuestActionPayload;
import com.jsirgalaxybase.terminal.TerminalQuestCenterSectionSnapshot;
import com.jsirgalaxybase.terminal.TerminalQuestParticipantActionPayload;
import com.jsirgalaxybase.terminal.TerminalQuestDraftEditPayload;
import com.jsirgalaxybase.terminal.client.viewmodel.TerminalHomeScreenModel;
import com.jsirgalaxybase.ui2.terminal.QuestCenterActionPort;
import com.jsirgalaxybase.ui2.terminal.QuestCenterVisualDocument;
import com.jsirgalaxybase.ui2.terminal.QuestManagementVisualDocument;
import com.jsirgalaxybase.ui2.terminal.QuestManagementVisualModel;
import com.jsirgalaxybase.ui2.terminal.QuestManagementActionPort;
import com.jsirgalaxybase.ui2.terminal.QuestChapterManagementActionPort;
import com.jsirgalaxybase.ui2.terminal.QuestChapterManagementVisualDocument;
import com.jsirgalaxybase.ui2.terminal.QuestChapterManagementVisualModel;
import com.jsirgalaxybase.ui2.terminal.TerminalActionPort;
import com.jsirgalaxybase.ui2.core.UiContext;
import com.jsirgalaxybase.ui2.core.UiElement;
import com.jsirgalaxybase.ui2.geometry.UiSize;
import com.jsirgalaxybase.ui2.layout.LayoutSpec;

/** Live Minecraft adapter for the shared platform-neutral player quest center. */
public final class TerminalQuestCenterDocument extends QuestCenterVisualDocument implements TerminalPageDocument {
    public interface Actions { void sendQuest(TerminalActionType action,TerminalQuestActionPayload payload);void sendQuestParticipant(TerminalActionType action,TerminalQuestParticipantActionPayload payload);void sendQuestEdit(TerminalQuestDraftEditPayload payload);void sendQuestBatchRetire(com.jsirgalaxybase.terminal.TerminalQuestBatchRetirePayload payload);void sendQuestChapterEdit(com.jsirgalaxybase.terminal.TerminalQuestChapterEditPayload payload);void sendQuestChapterClone(com.jsirgalaxybase.terminal.TerminalQuestChapterClonePayload payload);void sendQuestChapterAlignment(com.jsirgalaxybase.terminal.TerminalQuestChapterAlignmentPayload payload);void sendQuestChapterOrder(com.jsirgalaxybase.terminal.TerminalQuestChapterOrderPayload payload); }
    private TerminalHomeScreenModel screenModel;private final Actions business;private final QuestActionsBridge questActions;private final ManagementActionsBridge managementActions;private final QuestManagementVisualDocument managementDocument;private final ChapterActionsBridge chapterActions;private final QuestChapterManagementVisualDocument chapterDocument;

    public TerminalQuestCenterDocument(TerminalHomeScreenModel model,final TerminalAppShell.Actions shell,final Actions business){
        this(model,shell,business,new Runnable(){public void run(){}},new QuestActionsBridge(model,business));
    }
    public TerminalQuestCenterDocument(TerminalHomeScreenModel model,final TerminalAppShell.Actions shell,final Actions business,Runnable invalidation){
        this(model,shell,business,invalidation,new QuestActionsBridge(model,business));
    }
    private TerminalQuestCenterDocument(TerminalHomeScreenModel model,final TerminalAppShell.Actions shell,final Actions business,Runnable invalidation,QuestActionsBridge bridge){
        super(visual(model),new TerminalActionPort(){public void navigate(String id){shell.navigate(id);}
        public void refresh(){shell.refresh();}
        public void help(){shell.help();}
        public void back(){shell.back();}
        public void close(){shell.close();}},
            bridge,TerminalVisualModelAdapter.windowProfile(),invalidation);this.screenModel=model;this.business=business;this.questActions=bridge;
        TerminalActionPort shellPort=new TerminalActionPort(){public void navigate(String id){shell.navigate(id);}
        public void refresh(){shell.refresh();}
        public void help(){shell.help();}
        public void back(){shell.back();}
        public void close(){shell.close();}};
        this.managementActions=new ManagementActionsBridge(model,business);this.managementDocument=new QuestManagementVisualDocument(managementVisual(model),shellPort,managementActions,TerminalVisualModelAdapter.windowProfile(),invalidation);
        this.chapterActions=new ChapterActionsBridge(model,business);this.chapterDocument=new QuestChapterManagementVisualDocument(chapterVisual(model),shellPort,chapterActions,TerminalVisualModelAdapter.windowProfile(),invalidation);
    }
    @Override public void update(TerminalHomeScreenModel model){this.screenModel=model;questActions.update(model);managementActions.update(model);chapterActions.update(model);updateVisualModel(visual(model));managementDocument.update(managementVisual(model));chapterDocument.update(chapterVisual(model));}
    @Override public UiElement build(UiContext context){TerminalQuestCenterSectionSnapshot value=wire(screenModel);return value.getChapterManagement()!=null?chapterDocument.build(context):value.getView()==TerminalQuestCenterSectionSnapshot.View.ADMIN?managementDocument.build(context):super.build(context);}
    @Override public LayoutSpec layout(UiElement root,UiSize viewport,UiContext context){TerminalQuestCenterSectionSnapshot value=wire(screenModel);return value.getChapterManagement()!=null?chapterDocument.layout(root,viewport,context):value.getView()==TerminalQuestCenterSectionSnapshot.View.ADMIN?managementDocument.layout(root,viewport,context):super.layout(root,viewport,context);}
    @Override public void openHelp(){}
    @Override public boolean refresh(){send(TerminalActionType.REFRESH_PAGE,current());return true;}
    @Override public Map<String,ItemStack> externalItems(){TerminalQuestCenterSectionSnapshot wire=wire(screenModel);Map<String,ItemStack> result=new LinkedHashMap<String,ItemStack>();for(TerminalQuestCenterSectionSnapshot.Quest quest:wire.getQuests())put(result,"quest:icon:"+quest.getId(),quest.getIconRegistry(),quest.getIconMeta());if(wire.getDetail()!=null){put(result,"quest:detail:icon",wire.getDetail().getSummary().getIconRegistry(),wire.getDetail().getSummary().getIconMeta());int index=0;for(TerminalQuestCenterSectionSnapshot.Reward reward:wire.getDetail().getRewards()){put(result,"quest:reward:"+index,reward.getItemRegistry(),reward.getItemMeta());index++;}}return Collections.unmodifiableMap(result);}
    private void send(TerminalActionType action,TerminalQuestActionPayload payload){business.sendQuest(action,payload);}
    private TerminalQuestActionPayload current(){TerminalQuestCenterSectionSnapshot value=wire(screenModel);TerminalQuestCenterSectionSnapshot.Management management=value.getManagement();return new TerminalQuestActionPayload(value.getSelectedChapterId(),value.getSelectedQuestId(),value.getFilter(),value.getQuery(),value.getChapterPageIndex(),value.getQuestPageIndex(),"",-1,management==null?"":management.getLifecycle(),management==null?0:management.getPage());}
    private static final class QuestActionsBridge implements QuestCenterActionPort {private TerminalHomeScreenModel model;private final Actions actions;private QuestActionsBridge(TerminalHomeScreenModel model,Actions actions){this.model=model;this.actions=actions;}
        private void update(TerminalHomeScreenModel value){model=value;}
        private TerminalQuestActionPayload payload(){TerminalQuestCenterSectionSnapshot value=wire(model);return new TerminalQuestActionPayload(value.getSelectedChapterId(),value.getSelectedQuestId(),value.getFilter(),value.getQuery(),value.getChapterPageIndex(),value.getQuestPageIndex());}
        public void selectChapter(String id){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_SELECT_CHAPTER,new TerminalQuestActionPayload(id,"",p.getFilter(),p.getQuery(),p.getChapterPage(),0));}
        public void selectQuest(String id){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_SELECT_QUEST,new TerminalQuestActionPayload(p.getChapterId(),id,p.getFilter(),p.getQuery(),p.getChapterPage(),p.getQuestPage()));}
        public void changeFilter(String filter){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_CHANGE_FILTER,new TerminalQuestActionPayload(p.getChapterId(),"",filter,p.getQuery(),p.getChapterPage(),0));}
        public void changeQuery(String query){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_CHANGE_QUERY,new TerminalQuestActionPayload(p.getChapterId(),"",p.getFilter(),query,p.getChapterPage(),0));}
        public void changeChapterPage(int page){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_CHANGE_CHAPTER_PAGE,new TerminalQuestActionPayload(p.getChapterId(),"",p.getFilter(),p.getQuery(),page,p.getQuestPage()));}
        public void changeQuestPage(int page){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_CHANGE_QUEST_PAGE,new TerminalQuestActionPayload(p.getChapterId(),"",p.getFilter(),p.getQuery(),p.getChapterPage(),page));}
        public void backToBrowse(){actions.sendQuest(TerminalActionType.QUEST_BACK,payload());}
        public void claim(String id){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_CLAIM,new TerminalQuestActionPayload(p.getChapterId(),id,p.getFilter(),p.getQuery(),p.getChapterPage(),p.getQuestPage()));}
        public void selectRewardChoice(String questId,String rewardKey,int choiceIndex){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_SELECT_REWARD_CHOICE,new TerminalQuestActionPayload(p.getChapterId(),questId,p.getFilter(),p.getQuery(),p.getChapterPage(),p.getQuestPage(),rewardKey,choiceIndex));}
        public void toggleTracking(String questId){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_TOGGLE_TRACKING,new TerminalQuestActionPayload(p.getChapterId(),questId,p.getFilter(),p.getQuery(),p.getChapterPage(),p.getQuestPage()));}
        public void openManagement(){TerminalQuestActionPayload p=payload();actions.sendQuest(TerminalActionType.QUEST_ADMIN_OPEN,new TerminalQuestActionPayload(p.getChapterId(),"",p.getFilter(),p.getQuery(),p.getChapterPage(),p.getQuestPage(),"",-1,"",0));}
        public void createParticipant(String type,String name){actions.sendQuestParticipant(TerminalActionType.QUEST_PARTICIPANT_CREATE,new TerminalQuestParticipantActionPayload(type,"",name,"","",0L));}
        public void addParticipantMember(String type,String id,long revision,String player,String role){actions.sendQuestParticipant(TerminalActionType.QUEST_PARTICIPANT_ADD_MEMBER,new TerminalQuestParticipantActionPayload(type,id,"",player,role,revision));}
        public void removeParticipantMember(String type,String id,long revision,String player){actions.sendQuestParticipant(TerminalActionType.QUEST_PARTICIPANT_REMOVE_MEMBER,new TerminalQuestParticipantActionPayload(type,id,"",player,"",revision));}
        public void leaveParticipant(String type,String id,long revision){actions.sendQuestParticipant(TerminalActionType.QUEST_PARTICIPANT_LEAVE,new TerminalQuestParticipantActionPayload(type,id,"","","",revision));}
        public void transferParticipantOwner(String type,String id,long revision,String player){actions.sendQuestParticipant(TerminalActionType.QUEST_PARTICIPANT_TRANSFER_OWNER,new TerminalQuestParticipantActionPayload(type,id,"",player,"",revision));}
        public void retry(){actions.sendQuest(TerminalActionType.REFRESH_PAGE,payload());}}
    private static final class ManagementActionsBridge implements QuestManagementActionPort{private TerminalHomeScreenModel model;private final Actions actions;private ManagementActionsBridge(TerminalHomeScreenModel model,Actions actions){this.model=model;this.actions=actions;}
        private void update(TerminalHomeScreenModel value){model=value;}
        private TerminalQuestActionPayload payload(String id,int version,String lifecycle,int page,String hash){TerminalQuestCenterSectionSnapshot value=wire(model);return new TerminalQuestActionPayload("",id,"all",value.getQuery(),0,0,"",-1,lifecycle,page,version,hash);}
        private void edit(String id,int version,String hash,java.util.List<com.jsirgalaxybase.quest.core.QuestDraftEditOperation> operations){TerminalQuestCenterSectionSnapshot.Management current=wire(model).getManagement();actions.sendQuestEdit(new TerminalQuestDraftEditPayload(new com.jsirgalaxybase.quest.core.QuestDraftEditRequest(java.util.UUID.fromString(id),version,hash,operations),wire(model).getQuery(),current==null?"":current.getLifecycle(),current==null?0:current.getPage()));}
        public void back(){actions.sendQuest(TerminalActionType.QUEST_BACK,TerminalQuestActionPayload.empty());}
        public void openChapters(){actions.sendQuest(TerminalActionType.QUEST_CHAPTER_ADMIN_OPEN,TerminalQuestActionPayload.empty());}
        public void filter(String lifecycle){actions.sendQuest(TerminalActionType.QUEST_ADMIN_FILTER,payload("",0,lifecycle,0,""));}
        public void page(int page){TerminalQuestCenterSectionSnapshot.Management current=wire(model).getManagement();actions.sendQuest(TerminalActionType.QUEST_ADMIN_PAGE,payload("",0,current==null?"":current.getLifecycle(),page,""));}
        public void select(String id,int version){TerminalQuestCenterSectionSnapshot.Management current=wire(model).getManagement();actions.sendQuest(TerminalActionType.QUEST_ADMIN_SELECT,payload(id,version,current==null?"":current.getLifecycle(),current==null?0:current.getPage(),""));}
        public void closeDetail(){TerminalQuestCenterSectionSnapshot.Management current=wire(model).getManagement();actions.sendQuest(TerminalActionType.QUEST_ADMIN_PAGE,payload("",0,current==null?"":current.getLifecycle(),current==null?0:current.getPage(),""));}
        public void createDraft(String template,String name){actions.sendQuest(TerminalActionType.QUEST_ADMIN_CREATE,new TerminalQuestActionPayload("","","all",name,0,0,"",-1,"DRAFT",0,0,"",template));}
        public void publish(String id,int version,String hash){TerminalQuestCenterSectionSnapshot.Management current=wire(model).getManagement();actions.sendQuest(TerminalActionType.QUEST_ADMIN_PUBLISH,payload(id,version,current==null?"":current.getLifecycle(),current==null?0:current.getPage(),hash));}
        public void retire(String id,int version){TerminalQuestCenterSectionSnapshot.Management current=wire(model).getManagement();actions.sendQuest(TerminalActionType.QUEST_ADMIN_RETIRE,payload(id,version,current==null?"":current.getLifecycle(),current==null?0:current.getPage(),""));}
        public void batchRetire(java.util.List<String> ids,java.util.List<Integer> versions){if(ids==null||versions==null||ids.size()!=versions.size()||ids.size()<2)return;java.util.List<com.jsirgalaxybase.quest.core.QuestDefinitionBatchRetirementRequest.Target> targets=new java.util.ArrayList<com.jsirgalaxybase.quest.core.QuestDefinitionBatchRetirementRequest.Target>();for(int i=0;i<ids.size()&&i<128;i++)try{targets.add(new com.jsirgalaxybase.quest.core.QuestDefinitionBatchRetirementRequest.Target(java.util.UUID.fromString(ids.get(i)),versions.get(i).intValue()));}catch(RuntimeException ignored){}if(targets.size()<2)return;TerminalQuestCenterSectionSnapshot.Management current=wire(model).getManagement();actions.sendQuestBatchRetire(new com.jsirgalaxybase.terminal.TerminalQuestBatchRetirePayload(new com.jsirgalaxybase.quest.core.QuestDefinitionBatchRetirementRequest(targets),current==null?"":current.getQuery(),current==null?"":current.getLifecycle(),current==null?0:current.getPage()));}
        public void saveBasics(String id,int version,String hash,String name,String description,String prerequisiteLogic,String taskLogic){edit(id,version,hash,java.util.Arrays.asList(com.jsirgalaxybase.quest.core.QuestDraftEditOperation.name(name),com.jsirgalaxybase.quest.core.QuestDraftEditOperation.description(description),com.jsirgalaxybase.quest.core.QuestDraftEditOperation.prerequisiteLogic(com.jsirgalaxybase.quest.core.QuestLogic.valueOf(prerequisiteLogic)),com.jsirgalaxybase.quest.core.QuestDraftEditOperation.taskLogic(com.jsirgalaxybase.quest.core.QuestLogic.valueOf(taskLogic))));}
        public void savePrerequisites(String id,int version,String hash,java.util.List<String> original,java.util.List<String> selected){java.util.LinkedHashSet<String> before=new java.util.LinkedHashSet<String>(original),after=new java.util.LinkedHashSet<String>(selected);java.util.List<com.jsirgalaxybase.quest.core.QuestDraftEditOperation> operations=new java.util.ArrayList<com.jsirgalaxybase.quest.core.QuestDraftEditOperation>();for(String value:before)if(!after.contains(value))operations.add(com.jsirgalaxybase.quest.core.QuestDraftEditOperation.removePrerequisite(java.util.UUID.fromString(value)));for(String value:after)if(!before.contains(value))operations.add(com.jsirgalaxybase.quest.core.QuestDraftEditOperation.addPrerequisite(java.util.UUID.fromString(value)));if(!operations.isEmpty())edit(id,version,hash,operations);}
        public void saveOptions(String id,int version,String hash,java.util.Map<String,String> original,java.util.Map<String,String> selected){java.util.List<com.jsirgalaxybase.quest.core.QuestDraftEditOperation> operations=new java.util.ArrayList<com.jsirgalaxybase.quest.core.QuestDraftEditOperation>();for(java.util.Map.Entry<String,String> entry:selected.entrySet()){String before=original.get(entry.getKey());if(before==null||!before.equals(entry.getValue()))operations.add(com.jsirgalaxybase.quest.core.QuestDraftEditOperation.option(entry.getKey(),entry.getValue()));}if(!operations.isEmpty())edit(id,version,hash,operations);}
        public void saveElement(String id,int version,String hash,boolean task,String originalKey,String key,String typeId,boolean optional,java.util.Map<String,String> parameters){
            com.jsirgalaxybase.quest.core.QuestDraftEditOperation operation;
            if(task){com.jsirgalaxybase.quest.core.TaskDefinition value=new com.jsirgalaxybase.quest.core.TaskDefinition(key,typeId,optional,parameters);operation=originalKey.isEmpty()?com.jsirgalaxybase.quest.core.QuestDraftEditOperation.addTask(value):com.jsirgalaxybase.quest.core.QuestDraftEditOperation.replaceTask(originalKey,value);}
            else{com.jsirgalaxybase.quest.core.RewardDefinition value=new com.jsirgalaxybase.quest.core.RewardDefinition(key,typeId,parameters);operation=originalKey.isEmpty()?com.jsirgalaxybase.quest.core.QuestDraftEditOperation.addReward(value):com.jsirgalaxybase.quest.core.QuestDraftEditOperation.replaceReward(originalKey,value);}
            edit(id,version,hash,java.util.Collections.singletonList(operation));
        }
        public void deleteElement(String id,int version,String hash,boolean task,String key){edit(id,version,hash,java.util.Collections.singletonList(task?com.jsirgalaxybase.quest.core.QuestDraftEditOperation.removeTask(key):com.jsirgalaxybase.quest.core.QuestDraftEditOperation.removeReward(key)));}
        public void moveElement(String id,int version,String hash,boolean task,String key,int index){edit(id,version,hash,java.util.Collections.singletonList(task?com.jsirgalaxybase.quest.core.QuestDraftEditOperation.moveTask(key,index):com.jsirgalaxybase.quest.core.QuestDraftEditOperation.moveReward(key,index)));}
    }
    private static final class ChapterActionsBridge implements QuestChapterManagementActionPort{private TerminalHomeScreenModel model;private final Actions actions;private ChapterActionsBridge(TerminalHomeScreenModel model,Actions actions){this.model=model;this.actions=actions;}private void update(TerminalHomeScreenModel value){model=value;}
        private TerminalQuestActionPayload payload(String id,int version,String lifecycle,int page,String hash,String query){return new TerminalQuestActionPayload(id,"","all",query,0,0,"",-1,lifecycle,page,version,hash);}
        private TerminalQuestCenterSectionSnapshot.ChapterManagement current(){return wire(model).getChapterManagement();}
        private void edit(String id,int version,String hash,java.util.List<com.jsirgalaxybase.quest.core.QuestChapterEditOperation> operations){TerminalQuestCenterSectionSnapshot.ChapterManagement value=current();actions.sendQuestChapterEdit(new com.jsirgalaxybase.terminal.TerminalQuestChapterEditPayload(new com.jsirgalaxybase.quest.core.QuestChapterEditRequest(java.util.UUID.fromString(id),version,hash,operations),value==null?"":value.getQuery(),value==null?"":value.getLifecycle(),value==null?0:value.getPage()));}
        public void back(){actions.sendQuest(TerminalActionType.QUEST_ADMIN_OPEN,TerminalQuestActionPayload.empty());}
        public void filter(String value){actions.sendQuest(TerminalActionType.QUEST_CHAPTER_ADMIN_FILTER,payload("",0,value,0,"",""));}
        public void page(int page){TerminalQuestCenterSectionSnapshot.ChapterManagement value=current();actions.sendQuest(TerminalActionType.QUEST_CHAPTER_ADMIN_PAGE,payload("",0,value==null?"":value.getLifecycle(),page,"",value==null?"":value.getQuery()));}
        public void select(String id,int version){TerminalQuestCenterSectionSnapshot.ChapterManagement value=current();actions.sendQuest(TerminalActionType.QUEST_CHAPTER_ADMIN_SELECT,payload(id,version,value==null?"":value.getLifecycle(),value==null?0:value.getPage(),"",value==null?"":value.getQuery()));}
        public void closeDetail(){TerminalQuestCenterSectionSnapshot.ChapterManagement value=current();actions.sendQuest(TerminalActionType.QUEST_CHAPTER_ADMIN_PAGE,payload("",0,value==null?"":value.getLifecycle(),value==null?0:value.getPage(),"",value==null?"":value.getQuery()));}
        public void create(String name){actions.sendQuest(TerminalActionType.QUEST_CHAPTER_ADMIN_CREATE,payload("",0,"DRAFT",0,"",name));}
        public void publish(String id,int version,String hash){TerminalQuestCenterSectionSnapshot.ChapterManagement value=current();actions.sendQuest(TerminalActionType.QUEST_CHAPTER_ADMIN_PUBLISH,payload(id,version,value==null?"":value.getLifecycle(),value==null?0:value.getPage(),hash,value==null?"":value.getQuery()));}
        public void retire(String id,int version){TerminalQuestCenterSectionSnapshot.ChapterManagement value=current();actions.sendQuest(TerminalActionType.QUEST_CHAPTER_ADMIN_RETIRE,payload(id,version,value==null?"":value.getLifecycle(),value==null?0:value.getPage(),"",value==null?"":value.getQuery()));}
        public void saveBasics(String id,int version,String hash,String name,String description,String icon,String background,int backgroundSize,String visibility){edit(id,version,hash,java.util.Arrays.asList(com.jsirgalaxybase.quest.core.QuestChapterEditOperation.name(name),com.jsirgalaxybase.quest.core.QuestChapterEditOperation.description(description),com.jsirgalaxybase.quest.core.QuestChapterEditOperation.icon(icon),com.jsirgalaxybase.quest.core.QuestChapterEditOperation.background(background),com.jsirgalaxybase.quest.core.QuestChapterEditOperation.backgroundSize(backgroundSize),com.jsirgalaxybase.quest.core.QuestChapterEditOperation.visibility(com.jsirgalaxybase.quest.core.QuestVisibility.valueOf(visibility))));}
        public void place(String id,int version,String hash,String questId,int x,int y,int width,int height){edit(id,version,hash,java.util.Collections.singletonList(com.jsirgalaxybase.quest.core.QuestChapterEditOperation.place(java.util.UUID.fromString(questId),x,y,width,height)));}
        public void move(String id,int version,String hash,String questId,int x,int y){edit(id,version,hash,java.util.Collections.singletonList(com.jsirgalaxybase.quest.core.QuestChapterEditOperation.move(java.util.UUID.fromString(questId),x,y)));}
        public void resize(String id,int version,String hash,String questId,int width,int height){edit(id,version,hash,java.util.Collections.singletonList(com.jsirgalaxybase.quest.core.QuestChapterEditOperation.resize(java.util.UUID.fromString(questId),width,height)));}
        public void remove(String id,int version,String hash,String questId){edit(id,version,hash,java.util.Collections.singletonList(com.jsirgalaxybase.quest.core.QuestChapterEditOperation.remove(java.util.UUID.fromString(questId))));}
        public void removeEntries(String id,int version,String hash,java.util.List<String> questIds){java.util.List<com.jsirgalaxybase.quest.core.QuestChapterEditOperation> operations=new java.util.ArrayList<com.jsirgalaxybase.quest.core.QuestChapterEditOperation>();if(questIds!=null)for(String questId:questIds)try{operations.add(com.jsirgalaxybase.quest.core.QuestChapterEditOperation.remove(java.util.UUID.fromString(questId)));}catch(IllegalArgumentException ignored){}if(operations.size()>=2)edit(id,version,hash,operations);}
        public void cloneEntries(String id,int version,String hash,java.util.List<String> questIds,int anchorX,int anchorY){
            TerminalQuestCenterSectionSnapshot.ChapterManagement value=current();
            java.util.List<com.jsirgalaxybase.quest.core.QuestDefinitionCloneRequest.Source> sources=new java.util.ArrayList<com.jsirgalaxybase.quest.core.QuestDefinitionCloneRequest.Source>();
            if(questIds!=null)for(String questId:questIds)try{sources.add(new com.jsirgalaxybase.quest.core.QuestDefinitionCloneRequest.Source(java.util.UUID.fromString(questId),1));}catch(IllegalArgumentException ignored){}
            if(sources.isEmpty())return;
            actions.sendQuestChapterClone(new com.jsirgalaxybase.terminal.TerminalQuestChapterClonePayload(
                new com.jsirgalaxybase.quest.core.QuestChapterCloneRequest(java.util.UUID.fromString(id),version,hash,
                    new com.jsirgalaxybase.quest.core.QuestDefinitionCloneRequest(sources),anchorX,anchorY),
                value==null?"":value.getQuery(),value==null?"":value.getLifecycle(),value==null?0:value.getPage()));
        }
        public void align(String id,int version,String hash,java.util.List<String> questIds,String alignment){
            TerminalQuestCenterSectionSnapshot.ChapterManagement value=current();java.util.List<java.util.UUID> ids=new java.util.ArrayList<java.util.UUID>();
            if(questIds!=null)for(String questId:questIds)try{ids.add(java.util.UUID.fromString(questId));}catch(IllegalArgumentException ignored){}
            try{actions.sendQuestChapterAlignment(new com.jsirgalaxybase.terminal.TerminalQuestChapterAlignmentPayload(
                new com.jsirgalaxybase.quest.core.QuestChapterAlignmentRequest(java.util.UUID.fromString(id),version,hash,ids,
                    com.jsirgalaxybase.quest.core.QuestChapterAlignment.valueOf(alignment)),value==null?"":value.getQuery(),
                value==null?"":value.getLifecycle(),value==null?0:value.getPage()));}catch(IllegalArgumentException ignored){}
        }
        public void moveBefore(String chapterId,String beforeChapterId){
            TerminalQuestCenterSectionSnapshot.ChapterManagement value=current();
            try{actions.sendQuestChapterOrder(new com.jsirgalaxybase.terminal.TerminalQuestChapterOrderPayload(
                java.util.UUID.fromString(chapterId),beforeChapterId==null||beforeChapterId.isEmpty()?null:java.util.UUID.fromString(beforeChapterId),
                value==null?"":value.getQuery(),value==null?"":value.getLifecycle(),value==null?0:value.getPage()));
            }catch(IllegalArgumentException ignored){}
        }
    }
    private static com.jsirgalaxybase.ui2.terminal.QuestCenterVisualModel visual(TerminalHomeScreenModel model){return QuestCenterVisualModelAdapter.fromWire(TerminalVisualModelAdapter.shell(model),wire(model));}
    private static TerminalQuestCenterSectionSnapshot wire(TerminalHomeScreenModel model){if(model==null)return TerminalQuestCenterSectionSnapshot.unavailable("任务快照缺失");TerminalQuestCenterSectionSnapshot value=model.getPageSnapshot("career").getQuestCenterModel();return value==null?TerminalQuestCenterSectionSnapshot.unavailable("任务快照缺失"):value;}
    private static QuestManagementVisualModel managementVisual(TerminalHomeScreenModel model){TerminalQuestCenterSectionSnapshot wire=wire(model);TerminalQuestCenterSectionSnapshot.Management source=wire.getManagement();java.util.List<QuestManagementVisualModel.Definition> rows=new java.util.ArrayList<QuestManagementVisualModel.Definition>();if(source!=null)for(TerminalQuestCenterSectionSnapshot.Definition value:source.getDefinitions())rows.add(managedDefinition(value));QuestManagementVisualModel.Detail detail=null;if(source!=null&&source.getDetail()!=null){TerminalQuestCenterSectionSnapshot.DefinitionDetail value=source.getDetail();java.util.List<QuestManagementVisualModel.Element> tasks=managedElements(value.getTasks()),rewards=managedElements(value.getRewards());detail=new QuestManagementVisualModel.Detail(managedDefinition(value.getSummary()),value.getDescription(),value.getPrerequisiteLogic(),value.getTaskLogic(),value.getPrerequisites(),tasks,rewards,value.getOptions());}return new QuestManagementVisualModel(TerminalVisualModelAdapter.shell(model),source==null?wire.getQuery():source.getQuery(),source==null?"":source.getLifecycle(),wire.getMessage(),source==null?0:source.getPage(),source==null?20:source.getPageSize(),source==null?0:source.getTotal(),rows,detail,source==null?java.util.Collections.<QuestManagementVisualModel.ElementType>emptyList():managedTypes(source.getTaskTypes()),source==null?java.util.Collections.<QuestManagementVisualModel.ElementType>emptyList():managedTypes(source.getRewardTypes()),source==null?java.util.Collections.<QuestManagementVisualModel.Migration>emptyList():managedMigrations(source.getMigrations()));}
    private static QuestManagementVisualModel.Definition managedDefinition(TerminalQuestCenterSectionSnapshot.Definition value){return new QuestManagementVisualModel.Definition(value.getId(),value.getVersion(),value.getName(),value.getLifecycle(),value.getContentHash(),value.getPublishedAt(),value.getTaskCount(),value.getRewardCount());}
    private static QuestChapterManagementVisualModel chapterVisual(TerminalHomeScreenModel model){TerminalQuestCenterSectionSnapshot wire=wire(model);TerminalQuestCenterSectionSnapshot.ChapterManagement source=wire.getChapterManagement();java.util.List<QuestChapterManagementVisualModel.Chapter> rows=new java.util.ArrayList<QuestChapterManagementVisualModel.Chapter>();if(source!=null)for(TerminalQuestCenterSectionSnapshot.ManagedChapter value:source.getChapters())rows.add(chapter(value));QuestChapterManagementVisualModel.Detail detail=null;if(source!=null&&source.getDetail()!=null){TerminalQuestCenterSectionSnapshot.ChapterDetail value=source.getDetail();java.util.List<QuestChapterManagementVisualModel.Entry> entries=new java.util.ArrayList<QuestChapterManagementVisualModel.Entry>();for(TerminalQuestCenterSectionSnapshot.ChapterPlacement row:value.getPlacements())entries.add(new QuestChapterManagementVisualModel.Entry(row.getQuestId(),row.getName(),row.getX(),row.getY(),row.getWidth(),row.getHeight()));java.util.List<QuestChapterManagementVisualModel.QuestCandidate> candidates=new java.util.ArrayList<QuestChapterManagementVisualModel.QuestCandidate>();for(TerminalQuestCenterSectionSnapshot.ChapterCandidate row:value.getCandidates())candidates.add(new QuestChapterManagementVisualModel.QuestCandidate(row.getQuestId(),row.getName()));java.util.List<QuestChapterManagementVisualModel.Dependency> dependencies=new java.util.ArrayList<QuestChapterManagementVisualModel.Dependency>();for(TerminalQuestCenterSectionSnapshot.ChapterDependency row:value.getDependencies())dependencies.add(new QuestChapterManagementVisualModel.Dependency(row.getPrerequisiteQuestId(),row.getQuestId(),row.getKind()));detail=new QuestChapterManagementVisualModel.Detail(chapter(value.getSummary()),value.getDescription(),value.getIcon(),value.getBackground(),value.getBackgroundSize(),value.getVisibility(),entries,candidates,dependencies);}return new QuestChapterManagementVisualModel(TerminalVisualModelAdapter.shell(model),source==null?"":source.getQuery(),source==null?"":source.getLifecycle(),wire.getMessage(),source==null?0:source.getPage(),source==null?20:source.getPageSize(),source==null?0:source.getTotal(),rows,detail);}
    private static QuestChapterManagementVisualModel.Chapter chapter(TerminalQuestCenterSectionSnapshot.ManagedChapter value){return new QuestChapterManagementVisualModel.Chapter(value.getId(),value.getVersion(),value.getName(),value.getLifecycle(),value.getContentHash(),value.getEntryCount());}
    private static java.util.List<QuestManagementVisualModel.Element> managedElements(java.util.List<TerminalQuestCenterSectionSnapshot.Element> values){java.util.List<QuestManagementVisualModel.Element> result=new java.util.ArrayList<QuestManagementVisualModel.Element>();for(TerminalQuestCenterSectionSnapshot.Element value:values)result.add(new QuestManagementVisualModel.Element(value.getKey(),value.getTypeId(),value.isOptional(),value.getParameters()));return result;}
    private static java.util.List<QuestManagementVisualModel.ElementType> managedTypes(java.util.List<TerminalQuestCenterSectionSnapshot.ElementType> values){java.util.List<QuestManagementVisualModel.ElementType> result=new java.util.ArrayList<QuestManagementVisualModel.ElementType>();for(TerminalQuestCenterSectionSnapshot.ElementType value:values){java.util.List<QuestManagementVisualModel.Field> fields=new java.util.ArrayList<QuestManagementVisualModel.Field>();for(TerminalQuestCenterSectionSnapshot.Field field:value.getFields())fields.add(new QuestManagementVisualModel.Field(field.getKey(),field.getLabel(),field.getType(),field.isRequired(),field.getMinimum(),field.getMaximum(),field.getOptions()));result.add(new QuestManagementVisualModel.ElementType(value.getId(),value.getName(),value.getKind(),fields));}return result;}
    private static java.util.List<QuestManagementVisualModel.Migration> managedMigrations(java.util.List<TerminalQuestCenterSectionSnapshot.Migration> values){java.util.List<QuestManagementVisualModel.Migration> result=new java.util.ArrayList<QuestManagementVisualModel.Migration>();for(TerminalQuestCenterSectionSnapshot.Migration value:values)result.add(new QuestManagementVisualModel.Migration(value.getBatchId(),value.getSourceHash(),value.getStatus(),value.getAppliedAt(),value.getCreated(),value.getVersioned(),value.getUnchanged(),value.getErrorCount(),value.getWarningCount(),value.getDiagnostic()));return result;}
    private static void put(Map<String,ItemStack> map,String key,String registry,int meta){if(registry==null||registry.isEmpty())return;Object found=Item.itemRegistry.getObject(registry);if(found instanceof Item)map.put(key,new ItemStack((Item)found,1,meta));}
}
