package com.jsirgalaxybase.terminal.client.ui2;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import com.jsirgalaxybase.terminal.TerminalActionType;
import com.jsirgalaxybase.terminal.TerminalMarketAccountCenterRow;
import com.jsirgalaxybase.terminal.client.component.TerminalMarketSectionState;
import com.jsirgalaxybase.terminal.client.viewmodel.TerminalHomeScreenModel;
import com.jsirgalaxybase.terminal.client.viewmodel.TerminalMarketSectionModel;
import com.jsirgalaxybase.ui2.component.ComponentUiDocument;
import com.jsirgalaxybase.ui2.component.StandardWidgets;
import com.jsirgalaxybase.ui2.component.UiActionHandler;
import com.jsirgalaxybase.ui2.core.UiContext;
import com.jsirgalaxybase.ui2.core.UiElement;
import com.jsirgalaxybase.ui2.core.UiNode;
import com.jsirgalaxybase.ui2.geometry.Insets;
import com.jsirgalaxybase.ui2.geometry.UiRect;
import com.jsirgalaxybase.ui2.geometry.UiSize;
import com.jsirgalaxybase.ui2.input.InputResult;
import com.jsirgalaxybase.ui2.input.UiEvent;
import com.jsirgalaxybase.ui2.input.UiInputHandler;
import com.jsirgalaxybase.ui2.input.UiInputNode;
import com.jsirgalaxybase.ui2.input.UiKeyCode;
import com.jsirgalaxybase.ui2.layout.LayoutKind;
import com.jsirgalaxybase.ui2.layout.LayoutSpec;
import com.jsirgalaxybase.ui2.render.DrawCommand;
import com.jsirgalaxybase.ui2.render.DrawList;

/** Progressive standard market: catalog, product detail, then focused action overlays. */
public final class TerminalStandardMarketDocument extends ComponentUiDocument implements TerminalPageDocument {
    public interface Actions { void sendMarket(TerminalActionType action, String payload); }
    private enum Overlay { NONE, ORDER, CANCEL, CONFIRM_ORDER, CONFIRM_CANCEL }
    private static final String CHART_ID="market-chart";
    private final TerminalMarketSectionState state; private final TerminalAppShell.Actions shell;
    private final Actions actions; private final Runnable invalidation; private final MarketRefreshClock refresh=new MarketRefreshClock();
    private final MarketChartRenderer charts=new MarketChartRenderer();
    private TerminalHomeScreenModel model; private Overlay overlay=Overlay.NONE; private boolean help;
    private int width,height,columns=2; private TerminalMarketAccountCenterRow cancelRow;

    public TerminalStandardMarketDocument(TerminalMarketSectionState state,TerminalHomeScreenModel model,
        TerminalAppShell.Actions shell,Actions actions,Runnable invalidation){super(StandardWidgets.create());this.state=state;this.model=model;this.shell=shell;this.actions=actions;this.invalidation=invalidation;state.applyModel(market());refresh.received();}
    @Override public void update(TerminalHomeScreenModel value){model=value;TerminalMarketSectionModel next=market();if(state.acceptsModel(next))state.applyModel(next);refresh.received();}
    @Override public void openHelp(){help=true;invalidation.run();}
    @Override public boolean refresh(){requestRefresh();return true;}
    @Override public void tick(){if(refresh.tick(overlay==Overlay.NONE&&!state.hasFocusedField()))requestRefresh();}

    @Override public UiElement build(UiContext context){UiElement content=state.isStandardizedDetailView()?detail():catalog();UiElement.Builder stack=UiElement.type("Stack").key("std-root").child(content);if(overlay!=Overlay.NONE)stack.child(overlay());if(help)stack.child(UiElement.type("Dialog").key("std-help").prop(StandardWidgets.TEXT,"标准市场帮助").prop(StandardWidgets.DETAIL,"浏览商品后进入完整行情。买入、卖出和撤单只在需要时打开，结算仍由服务器重新核验。").prop(StandardWidgets.CANCEL_TEXT,"关闭").build());return TerminalAppShell.build(model,stack.build(),shell,state.isStandardizedDetailView()?"标准商品 · "+market().getSelectedProductName():"标准商品市场");}

    private UiElement catalog(){TerminalMarketSectionModel m=market();UiElement.Builder grid=UiElement.type("Grid").key("std-grid");List<TerminalMarketSectionModel.CatalogProductModel> products=m.getCatalogProducts();int visible=Math.min(products.size(),8);if(visible==0)grid.child(UiElement.type("EmptyState").key("std-empty").prop(StandardWidgets.TEXT,emptyMessage(m)).build());for(int index=0;index<visible;index++)grid.child(productCard(products.get(index),index));
        return UiElement.type("Column").key("std-catalog").child(UiElement.type("Row").key("std-catalog-head").child(field("std-query","搜索物品名称…",new Binding(){public String get(){return state.getBrowserQuery();}public void set(String v){state.setBrowserQuery(v);}})).child(button("std-search","搜索",true,new Runnable(){public void run(){state.submitBrowserQuery(state.getBrowserQuery());requestRefresh();}})).child(button("std-filter","筛选 · "+state.getBrowserFilterLabel(),true,new Runnable(){public void run(){state.cycleBrowserFilter();requestRefresh();}})).child(button("std-sort","排序 · "+state.getBrowserSortLabel(),true,new Runnable(){public void run(){state.cycleBrowserSort();requestRefresh();}})).build()).child(grid.build()).child(UiElement.type("Row").key("std-pager").child(button("std-prev","‹",m.hasCatalogPreviousPage(),new Runnable(){public void run(){state.setBrowserPage(m.getCatalogPageIndex()-1);requestRefresh();}})).child(label("std-page",(m.getCatalogPageIndex()+1)+" / "+Math.max(1,m.getCatalogTotalPages())+" · "+refresh.label(),false,"textMuted")).child(button("std-next","›",m.hasCatalogNextPage(),new Runnable(){public void run(){state.setBrowserPage(m.getCatalogPageIndex()+1);requestRefresh();}})).build()).build();}

    private UiElement productCard(final TerminalMarketSectionModel.CatalogProductModel p,int index){String id="market-item-"+index,zone="market-hover-"+index,mini="market-mini-"+index;return UiElement.type("Card").key("std-product-"+index).prop(StandardWidgets.TONE,p.getProductKey().equals(state.getSelectedProductKey())?"accent":"border").prop(StandardWidgets.ACTION,handler(new Runnable(){public void run(){state.requestDetailProduct(p.getProductKey());state.setSelectedProductKey(p.getProductKey());requestRefresh();}})).child(UiElement.type("Row").key("std-product-body-"+index).child(UiElement.type("ExternalItem").key("std-product-icon-"+index).prop(StandardWidgets.EXTERNAL_ID,id).build()).child(UiElement.type("Column").key("std-product-text-"+index).child(label("std-product-name-"+index,p.getDisplayName(),true,"text")).child(label("std-product-price-"+index,p.getMarketSummary().getLatestTrade()+"  "+p.getMarketSummary().getDayChange(),false,tone(p.getMarketSummary().getDayChange()))).child(UiElement.type("ExternalSurface").key("std-product-mini-"+index).prop(StandardWidgets.EXTERNAL_ID,mini).build()).build()).build()).child(UiElement.type("ExternalSurface").key("std-product-zone-"+index).prop(StandardWidgets.EXTERNAL_ID,zone).build()).build();}

    private UiElement detail(){final TerminalMarketSectionModel m=market();return UiElement.type("Column").key("std-detail").child(UiElement.type("Row").key("std-detail-head").child(button("std-back","‹ 商品目录",true,new Runnable(){public void run(){state.returnToStandardizedBrowse();invalidation.run();}})).child(label("std-fresh",refresh.label(),false,"textMuted")).child(range("1h")).child(range("24h")).child(range("7d")).build()).child(UiElement.type("Row").key("std-detail-work").child(summaryPanel(m)).child(UiElement.type("Card").key("std-chart-card").child(UiElement.type("ExternalSurface").key("std-chart").prop(StandardWidgets.EXTERNAL_ID,CHART_ID).build()).build()).build()).build();}

    private UiElement summaryPanel(final TerminalMarketSectionModel m){UiElement.Builder book=UiElement.type("Column").key("std-book").child(label("std-book-head","买盘        最近成交        卖盘",true,"textMuted"));for(int i=0;i<5;i++)book.child(label("std-book-"+i,"买"+(i+1)+" "+at(m.getBidLines(),i)+"  |  "+(i==0?m.getLatestTradePrice():"--")+"  |  卖"+(i+1)+" "+at(m.getAskLines(),i),false,"text"));return UiElement.type("Card").key("std-summary").child(UiElement.type("Row").key("std-product-hero").child(UiElement.type("ExternalItem").key("std-detail-icon").prop(StandardWidgets.EXTERNAL_ID,"market-detail-item").build()).child(UiElement.type("Column").key("std-hero-text").child(label("std-detail-name",m.getSelectedProductName(),true,"text")).child(label("std-detail-price",m.getLatestTradePrice(),true,"accent")).build()).build()).child(book.build()).child(label("std-day","24h 高/低  "+highLow(selectedPoints())+" · 量 "+m.getVolume24h()+" · 额 "+m.getTurnover24h(),false,"textMuted")).child(label("std-account-state","可用 "+m.getSourceAvailable()+" · 锁定 "+m.getLockedEscrowQuantity()+" · 待收 "+m.getClaimableQuantity()+" · 冻结 "+m.getFrozenFunds(),false,"textMuted")).child(UiElement.type("Row").key("std-actions").child(button("std-buy","买入",true,new Runnable(){public void run(){state.setOrderSide(TerminalMarketSectionState.OrderSide.BUY);overlay=Overlay.ORDER;invalidation.run();}})).child(button("std-sell","卖出",true,new Runnable(){public void run(){state.setOrderSide(TerminalMarketSectionState.OrderSide.SELL);overlay=Overlay.ORDER;invalidation.run();}})).child(button("std-cancel","撤单",hasCancelable(m),new Runnable(){public void run(){overlay=Overlay.CANCEL;invalidation.run();}})).child(button("std-history","订单中心",true,new Runnable(){public void run(){shell.navigate("market_account_center");}})).build()).build();}

    private UiElement range(final String value){return tab("std-range-"+value,value,value.equals(state.getSelectedChartRange()),new Runnable(){public void run(){state.setSelectedChartRange(value);requestRefresh();}});}

    private UiElement overlay(){if(overlay==Overlay.CONFIRM_ORDER)return dialog("std-confirm-order","确认提交订单",orderSummary(),"提交订单");if(overlay==Overlay.CONFIRM_CANCEL)return dialog("std-confirm-cancel","确认撤单",cancelSummary(),"确认撤单");if(overlay==Overlay.CANCEL)return cancelSelector();return orderEntry();}
    private UiElement orderEntry(){TerminalMarketSectionModel m=market();return UiElement.type("Surface").key("std-overlay").prop(StandardWidgets.ACTION,handler(new Runnable(){public void run(){overlay=Overlay.NONE;invalidation.run();}})).child(UiElement.type("Card").key("std-order-popup").child(label("std-order-title",(state.getOrderSide()==TerminalMarketSectionState.OrderSide.BUY?"买入 ":"卖出 ")+m.getSelectedProductName(),true,"text")).child(UiElement.type("Row").key("std-order-type").child(tab("std-market","市价",state.getOrderType()==TerminalMarketSectionState.OrderType.MARKET,new Runnable(){public void run(){state.setOrderType(TerminalMarketSectionState.OrderType.MARKET);invalidation.run();}})).child(tab("std-limit","限价",state.getOrderType()==TerminalMarketSectionState.OrderType.LIMIT,new Runnable(){public void run(){state.setOrderType(TerminalMarketSectionState.OrderType.LIMIT);invalidation.run();}})).build()).child(field("std-price","价格",new Binding(){public String get(){return price();}public void set(String v){setPrice(v);}})).child(UiElement.type("Row").key("std-price-shortcuts").child(shortcut("std-bid","买一",m.getHighestBid(),true)).child(shortcut("std-last","最新",m.getLatestTradePrice(),true)).child(shortcut("std-ask","卖一",m.getLowestAsk(),true)).build()).child(field("std-quantity","数量",new Binding(){public String get(){return quantity();}public void set(String v){setQuantity(v);}})).child(UiElement.type("Row").key("std-quantity-shortcuts").child(quantityShortcut("std-q25","25%",25,m)).child(quantityShortcut("std-q50","50%",50,m)).child(quantityShortcut("std-qmax","最大",100,m)).build()).child(label("std-settlement",preview(m)+" · 服务端提交时重新计算费用",false,"textMuted")).child(label("std-disabled",disabledReason(m),false,state.hasCompleteOrderTicket()?"success":"danger")).child(UiElement.type("Row").key("std-order-buttons").child(button("std-order-close","取消",true,new Runnable(){public void run(){overlay=Overlay.NONE;invalidation.run();}})).child(button("std-order-next","核对订单",state.hasCompleteOrderTicket(),new Runnable(){public void run(){overlay=Overlay.CONFIRM_ORDER;invalidation.run();}})).build()).build()).build();}

    private UiElement cancelSelector(){TerminalMarketSectionModel m=market();UiElement.Builder list=UiElement.type("Column").key("std-cancel-list");int shown=0;for(final TerminalMarketAccountCenterRow row:m.getAccountCenterRows()){if(!row.isCancelable()||!sameProduct(row,m))continue;if(shown++>=4)break;list.child(button("std-cancel-row-"+shown,("BUY".equals(row.getSide())?"买 ":"卖 ")+row.getUnitPrice()+" · 成交 "+row.getFilledQuantity()+"/"+row.getOriginalQuantity()+" · 剩余 "+row.getRemainingQuantity(),true,new Runnable(){public void run(){cancelRow=row;state.prepareCancelOrder(row.getRecordId(),row.getUpdatedAtEpochSeconds());overlay=Overlay.CONFIRM_CANCEL;invalidation.run();}}));}if(shown==0)list.child(UiElement.type("EmptyState").key("std-cancel-empty").prop(StandardWidgets.TEXT,"当前商品没有可撤剩余委托").build());return UiElement.type("Surface").key("std-overlay").prop(StandardWidgets.ACTION,handler(new Runnable(){public void run(){overlay=Overlay.NONE;invalidation.run();}})).child(UiElement.type("Card").key("std-cancel-popup").child(label("std-cancel-title","当前商品委托",true,"text")).child(list.build()).child(button("std-cancel-close","关闭",true,new Runnable(){public void run(){overlay=Overlay.NONE;invalidation.run();}})).build()).build();}

    private UiElement dialog(String key,String title,String detail,String confirmText){return UiElement.type("Dialog").key(key).prop(StandardWidgets.TEXT,title).prop(StandardWidgets.DETAIL,detail).prop(StandardWidgets.CANCEL_TEXT,"返回").prop(StandardWidgets.CONFIRM_TEXT,confirmText).build();}

    @Override public LayoutSpec layout(UiElement root,UiSize viewport,UiContext context){width=viewport.getWidth();height=viewport.getHeight();UiRect window=TerminalWindowMetrics.compute(viewport).getBounds();columns=window.getWidth()>=560?4:window.getWidth()>=400?3:2;LayoutSpec content=state.isStandardizedDetailView()?detailLayout():catalogLayout();LayoutSpec.Builder stack=LayoutSpec.of("std-root",LayoutKind.STACK).flex(1F).child(content);if(overlay!=Overlay.NONE)stack.child(overlayLayout());if(help)stack.child(LayoutSpec.of("std-help",LayoutKind.LEAF).build());return TerminalAppShell.layout(viewport,model,stack.build());}
    private LayoutSpec catalogLayout(){LayoutSpec.Builder grid=LayoutSpec.of("std-grid",LayoutKind.GRID).columns(columns).flex(1F).gap(3);int visible=Math.min(market().getCatalogProducts().size(),8);if(visible==0)grid.child(LayoutSpec.of("std-empty",LayoutKind.LEAF).flex(1F).build());for(int i=0;i<visible;i++)grid.child(productLayout(i));LayoutSpec head=LayoutSpec.of("std-catalog-head",LayoutKind.ROW).preferred(0,18).gap(3).child(LayoutSpec.of("std-query",LayoutKind.LEAF).flex(1F).build()).child(fixed("std-search",42)).child(fixed("std-filter",72)).child(fixed("std-sort",68)).build();LayoutSpec pager=LayoutSpec.of("std-pager",LayoutKind.ROW).preferred(0,17).gap(3).child(fixed("std-prev",24)).child(LayoutSpec.of("std-page",LayoutKind.LEAF).flex(1F).build()).child(fixed("std-next",24)).build();return LayoutSpec.of("std-catalog",LayoutKind.COLUMN).padding(new Insets(4,5,4,5)).gap(3).child(head).child(grid.build()).child(pager).build();}
    private LayoutSpec productLayout(int i){return LayoutSpec.of("std-product-"+i,LayoutKind.STACK).flex(1F).child(LayoutSpec.of("std-product-zone-"+i,LayoutKind.LEAF).build()).child(LayoutSpec.of("std-product-body-"+i,LayoutKind.ROW).padding(new Insets(5,5,5,5)).gap(4).child(LayoutSpec.of("std-product-icon-"+i,LayoutKind.LEAF).preferred(24,24).build()).child(LayoutSpec.of("std-product-text-"+i,LayoutKind.COLUMN).flex(1F).gap(1).child(line("std-product-name-"+i,12)).child(line("std-product-price-"+i,10)).child(LayoutSpec.of("std-product-mini-"+i,LayoutKind.LEAF).flex(1F).build()).build()).build()).build();}
    private LayoutSpec detailLayout(){boolean compact=TerminalWindowMetrics.compute(new UiSize(width,height)).getBounds().getHeight()<=220;LayoutSpec head=LayoutSpec.of("std-detail-head",LayoutKind.ROW).preferred(0,17).gap(3).child(fixed("std-back",62)).child(LayoutSpec.of("std-fresh",LayoutKind.LEAF).flex(1F).build()).child(fixed("std-range-1h",30)).child(fixed("std-range-24h",34)).child(fixed("std-range-7d",30)).build();LayoutSpec hero=LayoutSpec.of("std-product-hero",LayoutKind.ROW).preferred(0,32).gap(4).child(LayoutSpec.of("std-detail-icon",LayoutKind.LEAF).preferred(28,28).build()).child(LayoutSpec.of("std-hero-text",LayoutKind.COLUMN).flex(1F).child(line("std-detail-name",13)).child(LayoutSpec.of("std-detail-price",LayoutKind.LEAF).flex(1F).build()).build()).build();LayoutSpec.Builder book=LayoutSpec.of("std-book",LayoutKind.COLUMN).flex(1F).gap(1).child(line("std-book-head",10));for(int i=0;i<5;i++)book.child(LayoutSpec.of("std-book-"+i,LayoutKind.LEAF).flex(1F).build());LayoutSpec acts=LayoutSpec.of("std-actions",LayoutKind.ROW).preferred(0,18).gap(2).child(LayoutSpec.of("std-buy",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("std-sell",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("std-cancel",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("std-history",LayoutKind.LEAF).flex(1F).build()).build();LayoutSpec summary=LayoutSpec.of("std-summary",LayoutKind.COLUMN).preferred(compact?118:160,0).padding(new Insets(4,5,4,5)).gap(2).child(hero).child(book.build()).child(line("std-day",11)).child(line("std-account-state",11)).child(acts).build();LayoutSpec chart=LayoutSpec.of("std-chart-card",LayoutKind.COLUMN).flex(1F).padding(new Insets(3,3,3,3)).child(LayoutSpec.of("std-chart",LayoutKind.LEAF).flex(1F).build()).build();return LayoutSpec.of("std-detail",LayoutKind.COLUMN).padding(new Insets(4,5,4,5)).gap(3).child(head).child(LayoutSpec.of("std-detail-work",LayoutKind.ROW).flex(1F).gap(3).child(summary).child(chart).build()).build();}
    private LayoutSpec overlayLayout(){if(overlay==Overlay.CONFIRM_ORDER)return LayoutSpec.of("std-confirm-order",LayoutKind.LEAF).build();if(overlay==Overlay.CONFIRM_CANCEL)return LayoutSpec.of("std-confirm-cancel",LayoutKind.LEAF).build();boolean cancel=overlay==Overlay.CANCEL;String popup=cancel?"std-cancel-popup":"std-order-popup";int popupWidth=Math.min(260,Math.max(180,width-70));int popupHeight=Math.min(cancel?135:180,Math.max(110,height-45));LayoutSpec.Builder p=LayoutSpec.of(popup,LayoutKind.COLUMN).preferred(popupWidth,popupHeight).padding(new Insets(7,8,7,8)).gap(3).child(line(cancel?"std-cancel-title":"std-order-title",14));if(cancel){LayoutSpec.Builder list=LayoutSpec.of("std-cancel-list",LayoutKind.COLUMN).flex(1F).gap(2);int shown=Math.min(4,cancelCount(market()));if(shown==0)list.child(LayoutSpec.of("std-cancel-empty",LayoutKind.LEAF).flex(1F).build());for(int i=1;i<=shown;i++)list.child(LayoutSpec.of("std-cancel-row-"+i,LayoutKind.LEAF).flex(1F).build());p.child(list.build()).child(line("std-cancel-close",17));}else p.child(pair("std-order-type","std-market","std-limit")).child(line("std-price",18)).child(triple("std-price-shortcuts","std-bid","std-last","std-ask")).child(line("std-quantity",18)).child(triple("std-quantity-shortcuts","std-q25","std-q50","std-qmax")).child(line("std-settlement",12)).child(line("std-disabled",12)).child(pair("std-order-buttons","std-order-close","std-order-next"));return LayoutSpec.of("std-overlay",LayoutKind.STACK).padding(new Insets(Math.max(8,(height-popupHeight)/2),Math.max(20,(width-popupWidth)/2),8,20)).child(p.build()).build();}

    @Override public UiInputNode modalInput(UiNode root,UiContext context){String key=help?"std-help":overlay==Overlay.CONFIRM_ORDER?"std-confirm-order":overlay==Overlay.CONFIRM_CANCEL?"std-confirm-cancel":overlay!=Overlay.NONE?"std-overlay":null;if(key==null)return null;final UiNode node=find(root,key);if(node==null)return null;if(overlay==Overlay.CONFIRM_ORDER||overlay==Overlay.CONFIRM_CANCEL||help)return confirmInput(key,node.getBounds());return widgets().input(node,context);}
    private UiInputNode confirmInput(String key,UiRect bounds){return new UiInputNode(key,bounds,true,new UiInputHandler(){public InputResult handle(UiInputNode target,UiEvent event){if(event.getPhase()!=UiEvent.Phase.TARGET)return InputResult.PASS;if(event.getType()==UiEvent.Type.KEY_DOWN&&event.getKeyCode()==UiKeyCode.ESCAPE){backOverlay();return InputResult.CONSUMED;}if(help&&(event.getType()==UiEvent.Type.POINTER_DOWN||(event.getType()==UiEvent.Type.KEY_DOWN&&event.getKeyCode()==UiKeyCode.ENTER))){backOverlay();return InputResult.CONSUMED;}if(event.getType()==UiEvent.Type.KEY_DOWN&&event.getKeyCode()==UiKeyCode.ENTER){confirmAction();return InputResult.CONSUMED;}if(event.getType()==UiEvent.Type.POINTER_DOWN){if(confirmHit(event))confirmAction();else backOverlay();return InputResult.CONSUMED;}return InputResult.PASS;}});}

    @Override public Map<String,ItemStack> externalItems(){Map<String,ItemStack> items=new LinkedHashMap<String,ItemStack>();List<TerminalMarketSectionModel.CatalogProductModel> p=market().getCatalogProducts();if(!state.isStandardizedDetailView()){int n=Math.min(p.size(),8);for(int i=0;i<n;i++){ItemStack stack=stack(p.get(i));if(stack!=null)items.put("market-item-"+i,stack);}}else{ItemStack stack=stack(selectedProduct());if(stack!=null)items.put("market-detail-item",stack);}return Collections.unmodifiableMap(items);}
    @Override public void drawExternal(DrawList list,int mouseX,int mouseY,float partialTicks){Map<String,UiRect> regions=regions(list);if(state.isStandardizedDetailView())charts.drawDetail(regions.get(CHART_ID),selectedPoints(),mouseX,mouseY,height<=220,state.getSelectedChartRange(),market().getLatestTradePrice());else{List<TerminalMarketSectionModel.CatalogProductModel> p=market().getCatalogProducts();int n=Math.min(p.size(),8);for(int i=0;i<n;i++){charts.draw(regions.get("market-mini-"+i),p.get(i).getMarketSummary().getPricePoints(),-1,-1,true);charts.hoverCard(regions.get("market-hover-"+i),p.get(i),mouseX,mouseY);}}}
    @Override public boolean externalKey(char typedChar,int keyCode){if(keyCode==1&&state.isStandardizedDetailView()&&overlay==Overlay.NONE){state.returnToStandardizedBrowse();invalidation.run();return true;}return false;}

    private void confirmAction(){if(overlay==Overlay.CONFIRM_ORDER)actions.sendMarket(TerminalActionType.MARKET_CONFIRM_ORDER,state.toUnifiedOrderPayload().encodeUnifiedOrder());else if(overlay==Overlay.CONFIRM_CANCEL)actions.sendMarket(TerminalActionType.MARKET_CANCEL_ORDER,state.toHistoryPayload().encodeHistory());overlay=Overlay.NONE;cancelRow=null;invalidation.run();}
    private void backOverlay(){if(help){help=false;}else if(overlay==Overlay.CONFIRM_ORDER)overlay=Overlay.ORDER;else if(overlay==Overlay.CONFIRM_CANCEL)overlay=Overlay.CANCEL;else overlay=Overlay.NONE;invalidation.run();}
    private boolean confirmHit(UiEvent e){int dw=Math.min(230,Math.max(80,width-40)),dh=Math.min(90,Math.max(50,height-30)),dx=(width-dw)/2,dy=(height-dh)/2,half=Math.max(0,(dw-28)/2);return new UiRect(dx+18+half,dy+dh-22,half,16).contains(e.getX(),e.getY());}
    private void requestRefresh(){refresh.requested();actions.sendMarket(TerminalActionType.MARKET_REFRESH,state.toBrowsePayload().encodeUnifiedOrder());invalidation.run();}
    private String emptyMessage(TerminalMarketSectionModel m){return state.getBrowserQuery().isEmpty()?"正式商品目录暂无可交易商品":"没有匹配“"+state.getBrowserQuery()+"”的商品";}
    private String preview(TerminalMarketSectionModel m){if(state.getOrderSide()==TerminalMarketSectionState.OrderSide.BUY)return state.getOrderType()==TerminalMarketSectionState.OrderType.MARKET?m.getInstantBuyPreview():m.getLimitBuyPreview();return state.getOrderType()==TerminalMarketSectionState.OrderType.MARKET?m.getInstantSellPreview():m.getLimitSellPreview();}
    private String disabledReason(TerminalMarketSectionModel m){if(state.getSelectedProductKey().isEmpty())return "请先选择商品";if(quantity().isEmpty())return "请填写数量";if(state.getOrderType()==TerminalMarketSectionState.OrderType.LIMIT&&price().isEmpty())return "限价订单需要填写价格";return "订单参数完整；仍以服务器校验为准";}
    private String orderSummary(){return(state.getOrderSide()==TerminalMarketSectionState.OrderSide.BUY?"买入 ":"卖出 ")+market().getSelectedProductName()+"；"+(state.getOrderType()==TerminalMarketSectionState.OrderType.MARKET?"市价":"限价 "+price())+"；数量 "+quantity()+"；"+preview(market());}
    private String cancelSummary(){return cancelRow==null?"没有选择委托":"委托 "+cancelRow.getRecordId()+"；"+cancelRow.getSide()+"；价格 "+cancelRow.getUnitPrice()+"；成交 "+cancelRow.getFilledQuantity()+"/"+cancelRow.getOriginalQuantity()+"；剩余 "+cancelRow.getRemainingQuantity()+" 将按服务端规则返还。";}
    private String price(){return state.getOrderSide()==TerminalMarketSectionState.OrderSide.BUY?state.getLimitBuyPriceText():state.getLimitSellPriceText();}
    private String quantity(){if(state.getOrderSide()==TerminalMarketSectionState.OrderSide.BUY)return state.getOrderType()==TerminalMarketSectionState.OrderType.MARKET?state.getInstantBuyQuantityText():state.getLimitBuyQuantityText();return state.getOrderType()==TerminalMarketSectionState.OrderType.MARKET?state.getInstantSellQuantityText():state.getLimitSellQuantityText();}
    private void setPrice(String v){if(state.getOrderSide()==TerminalMarketSectionState.OrderSide.BUY)state.setLimitBuyPriceText(v);else state.setLimitSellPriceText(v);}
    private void setQuantity(String v){if(state.getOrderSide()==TerminalMarketSectionState.OrderSide.BUY){if(state.getOrderType()==TerminalMarketSectionState.OrderType.MARKET)state.setInstantBuyQuantityText(v);else state.setLimitBuyQuantityText(v);}else if(state.getOrderType()==TerminalMarketSectionState.OrderType.MARKET)state.setInstantSellQuantityText(v);else state.setLimitSellQuantityText(v);}
    private UiElement shortcut(String key,String text,final String value,boolean enabled){return button(key,text,enabled,new Runnable(){public void run(){setPrice(digits(value));invalidation.run();}});}
    private UiElement quantityShortcut(String key,String text,final int percent,final TerminalMarketSectionModel m){return button(key,text,true,new Runnable(){public void run(){long max=parse(state.getOrderSide()==TerminalMarketSectionState.OrderSide.BUY?m.getBestAskQuantity():m.getSourceAvailable());setQuantity(String.valueOf(Math.max(1,max*percent/100)));invalidation.run();}});}
    private boolean hasCancelable(TerminalMarketSectionModel m){return cancelCount(m)>0;}private int cancelCount(TerminalMarketSectionModel m){int n=0;for(TerminalMarketAccountCenterRow r:m.getAccountCenterRows())if(r.isCancelable()&&sameProduct(r,m))n++;return n;}private boolean sameProduct(TerminalMarketAccountCenterRow r,TerminalMarketSectionModel m){TerminalMarketSectionModel.CatalogProductModel p=selectedProduct();return p==null||r.getRegistryName().equals(p.getRegistryName());}
    private TerminalMarketSectionModel.CatalogProductModel selectedProduct(){String key=market().getSelectedProductKey();for(TerminalMarketSectionModel.CatalogProductModel p:market().getCatalogProducts())if(p.getProductKey().equals(key))return p;return null;}
    private List<TerminalMarketSectionModel.PricePointModel> selectedPoints(){TerminalMarketSectionModel.CatalogProductModel p=selectedProduct();return p==null?Collections.<TerminalMarketSectionModel.PricePointModel>emptyList():p.getMarketSummary().getPricePoints();}
    private String highLow(List<TerminalMarketSectionModel.PricePointModel> pts){long hi=0,lo=Long.MAX_VALUE;for(TerminalMarketSectionModel.PricePointModel p:pts){if(p.isEmpty())continue;hi=Math.max(hi,p.getHigh());lo=Math.min(lo,p.getLow());}return lo==Long.MAX_VALUE?"-- / --":hi+" / "+lo;}
    private ItemStack stack(TerminalMarketSectionModel.CatalogProductModel p){if(p==null)return null;Object found=Item.itemRegistry.getObject(p.getRegistryName());return found instanceof Item?new ItemStack((Item)found,1,p.getMeta()):null;}
    private Map<String,UiRect> regions(DrawList list){Map<String,UiRect> r=new LinkedHashMap<String,UiRect>();if(list!=null)for(DrawCommand c:list.ordered())if(c.getKind()==DrawCommand.Kind.EXTERNAL_REGION)r.put(c.getExternalId(),c.getBounds());return r;}
    private UiNode find(UiNode n,String key){if(n==null)return null;if(n.getElement().getKey()!=null&&key.equals(n.getElement().getKey().getValue()))return n;for(UiNode c:n.getChildren()){UiNode f=find(c,key);if(f!=null)return f;}return null;}
    private interface Binding{String get();void set(String value);}private UiElement field(String key,String placeholder,final Binding binding){return UiElement.type("TextField").key(key).prop(StandardWidgets.TEXT,binding.get()).prop(StandardWidgets.PLACEHOLDER,placeholder).prop(StandardWidgets.ACTION,new UiActionHandler(){public InputResult handle(UiEvent e){String s=binding.get();if(e.getType()==UiEvent.Type.TEXT_INPUT&&!Character.isISOControl(e.getTypedChar()))binding.set(s+e.getTypedChar());else if(e.getType()==UiEvent.Type.KEY_DOWN&&(e.getKeyCode()==UiKeyCode.BACKSPACE||e.getKeyCode()==UiKeyCode.DELETE))binding.set(s.isEmpty()?s:s.substring(0,s.length()-1));invalidation.run();return InputResult.CONSUMED;}}).build();}
    private static UiElement button(String key,String text,boolean enabled,Runnable action){return UiElement.type("Button").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.ENABLED,enabled).prop(StandardWidgets.ACTION,handler(action)).build();}private static UiElement tab(String key,String text,boolean selected,Runnable action){return UiElement.type("Tab").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.SELECTED,selected).prop(StandardWidgets.ACTION,handler(action)).build();}private static UiActionHandler handler(final Runnable r){return new UiActionHandler(){public InputResult handle(UiEvent e){r.run();return InputResult.CONSUMED;}};}private static UiElement label(String key,String text,boolean bold,String tone){return UiElement.type("Label").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.TEXT_ROLE,"caption").prop(StandardWidgets.MAX_LINES,1).prop(StandardWidgets.BOLD,bold).prop(StandardWidgets.TONE,tone).build();}
    private static LayoutSpec fixed(String key,int width){return LayoutSpec.of(key,LayoutKind.LEAF).preferred(width,0).build();}private static LayoutSpec line(String key,int height){return LayoutSpec.of(key,LayoutKind.LEAF).preferred(0,height).build();}private static LayoutSpec pair(String key,String a,String b){return LayoutSpec.of(key,LayoutKind.ROW).preferred(0,18).gap(3).child(LayoutSpec.of(a,LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of(b,LayoutKind.LEAF).flex(1F).build()).build();}private static LayoutSpec triple(String key,String a,String b,String c){return LayoutSpec.of(key,LayoutKind.ROW).preferred(0,17).gap(3).child(LayoutSpec.of(a,LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of(b,LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of(c,LayoutKind.LEAF).flex(1F).build()).build();}
    private static String at(List<String> values,int i){return values!=null&&i<values.size()?values.get(i):"--";}private static String tone(String change){return change!=null&&change.trim().startsWith("-")?"danger":"success";}private static String digits(String value){if(value==null)return"";StringBuilder b=new StringBuilder();for(int i=0;i<value.length();i++){char c=value.charAt(i);if(Character.isDigit(c))b.append(c);}return b.toString();}private static long parse(String v){try{return Long.parseLong(digits(v));}catch(RuntimeException e){return 0;}}
    private TerminalMarketSectionModel market(){TerminalHomeScreenModel.PageSnapshotModel page=model.getPageSnapshot("market");return page.hasMarketSectionModel()?page.getMarketSectionModel():TerminalMarketSectionModel.placeholder("market_standardized");}
}
