package com.jsirgalaxybase.terminal.client.ui2;

import java.util.List;

import com.jsirgalaxybase.terminal.TerminalActionType;
import com.jsirgalaxybase.terminal.TerminalServerToolsActionPayload;
import com.jsirgalaxybase.terminal.client.viewmodel.TerminalHomeScreenModel;
import com.jsirgalaxybase.terminal.client.viewmodel.TerminalServerToolsSectionModel;
import com.jsirgalaxybase.ui2.component.ComponentUiDocument;
import com.jsirgalaxybase.ui2.component.StandardWidgets;
import com.jsirgalaxybase.ui2.component.UiActionHandler;
import com.jsirgalaxybase.ui2.core.UiContext;
import com.jsirgalaxybase.ui2.core.UiElement;
import com.jsirgalaxybase.ui2.core.UiNode;
import com.jsirgalaxybase.ui2.geometry.Insets;
import com.jsirgalaxybase.ui2.geometry.UiRect;
import com.jsirgalaxybase.ui2.geometry.UiSize;
import com.jsirgalaxybase.ui2.input.InputResult;
import com.jsirgalaxybase.ui2.input.UiEvent;
import com.jsirgalaxybase.ui2.input.UiInputHandler;
import com.jsirgalaxybase.ui2.input.UiInputNode;
import com.jsirgalaxybase.ui2.input.UiKeyCode;
import com.jsirgalaxybase.ui2.layout.LayoutKind;
import com.jsirgalaxybase.ui2.layout.LayoutSpec;
import com.jsirgalaxybase.ui2.state.UiStore;

/** UI2 ServerTools workbench for warp, home and cross-server TPA operations. */
public final class TerminalServerToolsDocument extends ComponentUiDocument implements TerminalPageDocument {
    public interface Actions { void send(TerminalActionType action, TerminalServerToolsActionPayload payload); }
    private static final int MAX_ROWS=3;
    private final UiStore<ServerToolsUiState,ServerToolsUiAction> store;
    private final TerminalAppShell.Actions shellActions;private final Actions actions;
    private TerminalHomeScreenModel model;private int width,height;
    public TerminalServerToolsDocument(UiStore<ServerToolsUiState,ServerToolsUiAction> store,TerminalHomeScreenModel model,TerminalAppShell.Actions shellActions,Actions actions){super(StandardWidgets.create());this.store=store;this.model=model;this.shellActions=shellActions;this.actions=actions;}
    @Override public void update(TerminalHomeScreenModel value){model=value;}
    @Override public void openHelp(){store.dispatch(ServerToolsUiAction.of(ServerToolsUiAction.Type.OPEN_HELP));}

    @Override public UiElement build(UiContext context){TerminalServerToolsSectionModel tools=tools();ServerToolsUiState state=store.getState();
        UiElement tabs=UiElement.type("Row").key("tools-tabs").child(tab("tools-warp-tab","Warp",ServerToolsUiState.Tab.WARP)).child(tab("tools-home-tab","Home",ServerToolsUiState.Tab.HOME)).child(tab("tools-tpa-tab","TPA",ServerToolsUiState.Tab.TPA)).build();
        UiElement body=state.getTab()==ServerToolsUiState.Tab.HOME?home(tools):state.getTab()==ServerToolsUiState.Tab.TPA?tpa(tools):warp(tools);
        UiElement feedback=UiElement.type("Card").key("tools-feedback").child(label("tools-feedback-title",tools.getActionFeedback().getTitle(),"caption",1,true,"text"))
            .child(label("tools-feedback-body",tools.getActionFeedback().getBody()+" · 最近: "+tools.getRecentTransferSummary(),"caption",1,false,"textMuted")).build();
        UiElement base=UiElement.type("Column").key("tools-base").child(label("tools-title","跨服传送 · "+tools.getCurrentServerId(),"section",1,true,"text"))
            .child(label("tools-status",tools.getServiceState(),"caption",1,false,"textMuted")).child(tabs).child(body).child(feedback).build();
        UiElement.Builder page=UiElement.type("Stack").key("tools-page-root").child(base);
        if(state.hasConfirmation()){ServerToolsUiState.Confirmation c=state.getConfirmation();page.child(UiElement.type("Dialog").key("tools-confirm-dialog").prop(StandardWidgets.TEXT,c.getTitle()).prop(StandardWidgets.DETAIL,c.getDetail()).prop(StandardWidgets.CANCEL_TEXT,"取消").prop(StandardWidgets.CONFIRM_TEXT,c.getConfirmLabel()).build());}
        if(state.isHelpOpen())page.child(UiElement.type("Dialog").key("tools-help").prop(StandardWidgets.TEXT,"传送帮助").prop(StandardWidgets.DETAIL,"Warp、Home 与 TPA 最终都由当前服务器校验，并通过既有跨服 ticket 完成；终端不会自行决定玩家位置。").build());
        return TerminalAppShell.build(model,page.build(),shellActions,"跨服传送");}

    private UiElement warp(final TerminalServerToolsSectionModel tools){UiElement.Builder list=UiElement.type("Column").key("tools-warp-list");int count=Math.min(MAX_ROWS,tools.getWarpNames().size());for(int i=0;i<count;i++){final String name=tools.getWarpNames().get(i);String title=i<tools.getWarpLines().size()?tools.getWarpLines().get(i):name;list.child(button("tools-warp-"+i,title,!name.isEmpty(),new Runnable(){public void run(){store.dispatch(ServerToolsUiAction.select(ServerToolsUiAction.Type.SELECT_WARP,name));actions.send(TerminalActionType.SERVER_TOOLS_SELECT_WARP,TerminalServerToolsActionPayload.forWarp(name));}}));}
        String selected=store.getState().getSelectedWarp();UiElement detail=UiElement.type("Card").key("tools-warp-detail").child(label("tools-warp-name",tools.getSelectedWarpTitle(),"body",1,true,"text"))
            .child(label("tools-warp-target",tools.getSelectedTargetServerId()+" · "+tools.getSelectedTargetLocation(),"caption",1,false,"textMuted"))
            .child(button("tools-warp-go","确认传送",tools.isSelectedWarpEnabled()&&!selected.isEmpty(),confirm(new ServerToolsUiState.Confirmation(TerminalActionType.SERVER_TOOLS_CONFIRM_WARP,TerminalServerToolsActionPayload.forWarp(selected),"确认 Warp 传送","目标 "+tools.getSelectedTargetServerId()+"；"+tools.getSelectedWarpDescription(),"确认传送"))))
            .child(quick("tools-quick-home","默认 Home","home",tools)).child(quick("tools-quick-back","返回上次","back",tools)).child(quick("tools-quick-spawn","当前服出生点","spawn",tools)).build();
        return UiElement.type("Row").key("tools-warp-body").child(list.build()).child(detail).build();}

    private UiElement quick(String key,String text,final String action,TerminalServerToolsSectionModel tools){return button(key,text,true,confirm(new ServerToolsUiState.Confirmation(TerminalActionType.SERVER_TOOLS_CONFIRM_QUICK,TerminalServerToolsActionPayload.forQuickAction(action),"确认传送","在 "+tools.getCurrentServerId()+" 执行 "+action+"；服务端会校验有效落点。","确认传送")));}

    private UiElement home(final TerminalServerToolsSectionModel tools){UiElement.Builder list=UiElement.type("Column").key("tools-home-list");int count=Math.min(MAX_ROWS,tools.getHomeNames().size());for(int i=0;i<count;i++){final String name=tools.getHomeNames().get(i);String title=i<tools.getHomeLines().size()?tools.getHomeLines().get(i):name;list.child(button("tools-home-"+i,title,!name.isEmpty(),new Runnable(){public void run(){store.dispatch(ServerToolsUiAction.select(ServerToolsUiAction.Type.SELECT_HOME,name));actions.send(TerminalActionType.SERVER_TOOLS_SELECT_HOME,TerminalServerToolsActionPayload.forHome(name));}}));}
        final String selected=store.getState().getSelectedHome();final String draft=store.getState().getHomeDraft();UiElement detail=UiElement.type("Card").key("tools-home-detail").child(field("tools-home-draft",ServerToolsUiState.Field.HOME,draft,"Home 名称"))
            .child(button("tools-home-set","保存当前位置",!draft.isEmpty(),confirm(homeConfirm(TerminalActionType.SERVER_TOOLS_SET_HOME,draft,"设定 Home","把当前位置保存为 "+draft,"确认设定"))))
            .child(label("tools-home-location",tools.getSelectedHomeTargetServerId()+" · "+tools.getSelectedHomeTargetLocation(),"caption",1,false,"textMuted"))
            .child(button("tools-home-go","前往",!selected.isEmpty(),confirm(homeConfirm(TerminalActionType.SERVER_TOOLS_CONFIRM_HOME,selected,"前往 Home","传送到 "+selected,"确认传送"))))
            .child(button("tools-home-delete","删除",!selected.isEmpty(),confirm(homeConfirm(TerminalActionType.SERVER_TOOLS_DELETE_HOME,selected,"删除 Home","删除 "+selected+" 后无法恢复。","确认删除")))).build();
        return UiElement.type("Row").key("tools-home-body").child(list.build()).child(detail).build();}
    private static ServerToolsUiState.Confirmation homeConfirm(TerminalActionType action,String name,String title,String detail,String label){return new ServerToolsUiState.Confirmation(action,TerminalServerToolsActionPayload.forHome(name),title,detail,label);}

    private UiElement tpa(final TerminalServerToolsSectionModel tools){ServerToolsUiState state=store.getState();UiElement form=UiElement.type("Card").key("tools-tpa-form").child(field("tools-tpa-player",ServerToolsUiState.Field.TPA_PLAYER,state.getPlayerDraft(),"玩家名"))
            .child(field("tools-tpa-server",ServerToolsUiState.Field.TPA_SERVER,state.getServerDraft(),"目标服务器"))
            .child(button("tools-tpa-request","发送请求",!state.getPlayerDraft().isEmpty()&&!state.getServerDraft().isEmpty(),confirm(tpaConfirm(TerminalActionType.SERVER_TOOLS_TPA_REQUEST,state.getPlayerDraft(),state.getServerDraft(),"发送 TPA","对方接受后，源服才会发起跨服 ticket。","发送请求")))).build();
        UiElement.Builder pending=UiElement.type("Column").key("tools-tpa-pending");int count=Math.min(MAX_ROWS,tools.getTpaCounterpartyNames().size());for(int i=0;i<count;i++){final String player=tools.getTpaCounterpartyNames().get(i);final String server=i<tools.getTpaTargetServerIds().size()?tools.getTpaTargetServerIds().get(i):"";String direction=i<tools.getTpaDirections().size()?tools.getTpaDirections().get(i):"";String status=i<tools.getTpaStatusLabels().size()?tools.getTpaStatusLabels().get(i):"";final boolean incoming="INCOMING".equalsIgnoreCase(direction);pending.child(UiElement.type("Card").key("tools-tpa-row-"+i).child(label("tools-tpa-label-"+i,player+" · "+status,"caption",1,true,"text"))
                .child(button("tools-tpa-primary-"+i,incoming?"接受":"取消",true,confirm(tpaConfirm(incoming?TerminalActionType.SERVER_TOOLS_TPA_ACCEPT:TerminalActionType.SERVER_TOOLS_TPA_CANCEL,player,server,incoming?"接受 TPA":"取消 TPA",incoming?"接受后记录你的当前位置，等待请求者源服派发。":"取消仍待处理的请求。",incoming?"确认接受":"确认取消"))))
                .child(button("tools-tpa-deny-"+i,"拒绝",incoming,confirm(tpaConfirm(TerminalActionType.SERVER_TOOLS_TPA_DENY,player,server,"拒绝 TPA","该待处理请求会被关闭。","确认拒绝")))).build());}
        if(count==0)pending.child(UiElement.type("EmptyState").key("tools-tpa-empty").prop(StandardWidgets.TEXT,"没有待处理 TPA").build());return UiElement.type("Row").key("tools-tpa-body").child(form).child(pending.build()).build();}
    private static ServerToolsUiState.Confirmation tpaConfirm(TerminalActionType action,String player,String server,String title,String detail,String label){return new ServerToolsUiState.Confirmation(action,TerminalServerToolsActionPayload.forTpa(player,server),title,player+" · "+server+"。"+detail,label);}

    @Override public LayoutSpec layout(UiElement root,UiSize viewport,UiContext context){width=viewport.getWidth();height=viewport.getHeight();boolean compact=TerminalWindowMetrics.compute(viewport).getBounds().getHeight()<=220;LayoutSpec body=store.getState().getTab()==ServerToolsUiState.Tab.HOME?homeLayout(compact):store.getState().getTab()==ServerToolsUiState.Tab.TPA?tpaLayout(compact):warpLayout(compact);LayoutSpec base=LayoutSpec.of("tools-base",LayoutKind.COLUMN).padding(new Insets(3,4,3,4)).gap(2).child(LayoutSpec.of("tools-title",LayoutKind.LEAF).preferred(0,14).build()).child(LayoutSpec.of("tools-status",LayoutKind.LEAF).preferred(0,10).build()).child(LayoutSpec.of("tools-tabs",LayoutKind.ROW).preferred(0,compact?14:18).gap(2).child(LayoutSpec.of("tools-warp-tab",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("tools-home-tab",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("tools-tpa-tab",LayoutKind.LEAF).flex(1F).build()).build()).child(body).child(LayoutSpec.of("tools-feedback",LayoutKind.COLUMN).preferred(0,compact?25:34).padding(new Insets(3,4,3,4)).gap(1).child(LayoutSpec.of("tools-feedback-title",LayoutKind.LEAF).preferred(0,10).build()).child(LayoutSpec.of("tools-feedback-body",LayoutKind.LEAF).flex(1F).build()).build()).build();LayoutSpec.Builder page=LayoutSpec.of("tools-page-root",LayoutKind.STACK).flex(1F).child(base);if(store.getState().hasConfirmation())page.child(LayoutSpec.of("tools-confirm-dialog",LayoutKind.LEAF).build());if(store.getState().isHelpOpen())page.child(LayoutSpec.of("tools-help",LayoutKind.LEAF).build());return TerminalAppShell.layout(viewport,model,page.build());}
    private LayoutSpec warpLayout(boolean compact){LayoutSpec.Builder list=LayoutSpec.of("tools-warp-list",LayoutKind.COLUMN).preferred(compact?90:120,0).gap(2);for(int i=0;i<Math.min(MAX_ROWS,tools().getWarpNames().size());i++)list.child(LayoutSpec.of("tools-warp-"+i,LayoutKind.LEAF).flex(1F).build());LayoutSpec detail=LayoutSpec.of("tools-warp-detail",LayoutKind.COLUMN).flex(1F).padding(new Insets(3,4,3,4)).gap(2).child(LayoutSpec.of("tools-warp-name",LayoutKind.LEAF).preferred(0,12).build()).child(LayoutSpec.of("tools-warp-target",LayoutKind.LEAF).preferred(0,10).build()).child(LayoutSpec.of("tools-warp-go",LayoutKind.LEAF).preferred(0,compact?14:18).build()).child(LayoutSpec.of("tools-quick-home",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("tools-quick-back",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("tools-quick-spawn",LayoutKind.LEAF).flex(1F).build()).build();return LayoutSpec.of("tools-warp-body",LayoutKind.ROW).flex(1F).gap(3).child(list.build()).child(detail).build();}
    private LayoutSpec homeLayout(boolean compact){LayoutSpec.Builder list=LayoutSpec.of("tools-home-list",LayoutKind.COLUMN).preferred(compact?90:120,0).gap(2);for(int i=0;i<Math.min(MAX_ROWS,tools().getHomeNames().size());i++)list.child(LayoutSpec.of("tools-home-"+i,LayoutKind.LEAF).flex(1F).build());LayoutSpec detail=LayoutSpec.of("tools-home-detail",LayoutKind.COLUMN).flex(1F).padding(new Insets(3,4,3,4)).gap(2).child(LayoutSpec.of("tools-home-draft",LayoutKind.LEAF).preferred(0,compact?14:18).build()).child(LayoutSpec.of("tools-home-set",LayoutKind.LEAF).preferred(0,compact?14:18).build()).child(LayoutSpec.of("tools-home-location",LayoutKind.LEAF).preferred(0,10).build()).child(LayoutSpec.of("tools-home-go",LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("tools-home-delete",LayoutKind.LEAF).flex(1F).build()).build();return LayoutSpec.of("tools-home-body",LayoutKind.ROW).flex(1F).gap(3).child(list.build()).child(detail).build();}
    private LayoutSpec tpaLayout(boolean compact){LayoutSpec form=LayoutSpec.of("tools-tpa-form",LayoutKind.COLUMN).preferred(compact?116:150,0).padding(new Insets(3,4,3,4)).gap(2).child(LayoutSpec.of("tools-tpa-player",LayoutKind.LEAF).preferred(0,compact?14:18).build()).child(LayoutSpec.of("tools-tpa-server",LayoutKind.LEAF).preferred(0,compact?14:18).build()).child(LayoutSpec.of("tools-tpa-request",LayoutKind.LEAF).preferred(0,compact?14:18).build()).build();LayoutSpec.Builder pending=LayoutSpec.of("tools-tpa-pending",LayoutKind.COLUMN).flex(1F).gap(2);int count=Math.min(MAX_ROWS,tools().getTpaCounterpartyNames().size());if(count==0)pending.child(LayoutSpec.of("tools-tpa-empty",LayoutKind.LEAF).flex(1F).build());for(int i=0;i<count;i++)pending.child(LayoutSpec.of("tools-tpa-row-"+i,LayoutKind.ROW).flex(1F).padding(new Insets(2,3,2,3)).gap(2).child(LayoutSpec.of("tools-tpa-label-"+i,LayoutKind.LEAF).flex(1F).build()).child(LayoutSpec.of("tools-tpa-primary-"+i,LayoutKind.LEAF).preferred(42,0).build()).child(LayoutSpec.of("tools-tpa-deny-"+i,LayoutKind.LEAF).preferred(36,0).build()).build());return LayoutSpec.of("tools-tpa-body",LayoutKind.ROW).flex(1F).gap(3).child(form).child(pending.build()).build();}

    @Override public UiInputNode modalInput(UiNode root,UiContext context){final boolean confirm=store.getState().hasConfirmation();if(!confirm&&!store.getState().isHelpOpen())return null;return new UiInputNode(confirm?"tools-confirm-dialog":"tools-help",new UiRect(0,0,width,height),true,new UiInputHandler(){public InputResult handle(UiInputNode target,UiEvent event){if(event.getPhase()!=UiEvent.Phase.TARGET)return InputResult.PASS;if(event.getType()==UiEvent.Type.KEY_DOWN&&event.getKeyCode()==UiKeyCode.ENTER&&confirm){submit();return InputResult.CONSUMED;}if(event.getType()==UiEvent.Type.POINTER_DOWN&&confirm){int dw=Math.min(230,Math.max(80,width-40)),dh=Math.min(90,Math.max(50,height-30)),dx=(width-dw)/2,dy=(height-dh)/2,half=Math.max(0,(dw-28)/2);if(new UiRect(dx+10+half+8,dy+dh-22,half,16).contains(event.getX(),event.getY()))submit();else store.dispatch(ServerToolsUiAction.of(ServerToolsUiAction.Type.CLOSE_CONFIRM));return InputResult.CONSUMED;}if((event.getType()==UiEvent.Type.KEY_DOWN&&event.getKeyCode()==UiKeyCode.ESCAPE)||event.getType()==UiEvent.Type.POINTER_DOWN){store.dispatch(ServerToolsUiAction.of(confirm?ServerToolsUiAction.Type.CLOSE_CONFIRM:ServerToolsUiAction.Type.CLOSE_HELP));return InputResult.CONSUMED;}return InputResult.PASS;}});}
    private void submit(){ServerToolsUiState.Confirmation c=store.getState().getConfirmation();if(c!=null)actions.send(c.getAction(),c.getPayload());store.dispatch(ServerToolsUiAction.of(ServerToolsUiAction.Type.CLOSE_CONFIRM));}
    private UiElement tab(String key,String text,final ServerToolsUiState.Tab value){return UiElement.type("Tab").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.SELECTED,store.getState().getTab()==value).prop(StandardWidgets.ACTION,handler(new Runnable(){public void run(){store.dispatch(ServerToolsUiAction.tab(value));}})).build();}
    private UiElement field(String key,final ServerToolsUiState.Field field,String value,String placeholder){return UiElement.type("TextField").key(key).prop(StandardWidgets.TEXT,value).prop(StandardWidgets.PLACEHOLDER,placeholder).prop(StandardWidgets.FOCUSED,store.getState().getField()==field).prop(StandardWidgets.ACTION,new UiActionHandler(){public InputResult handle(UiEvent event){if(event.getType()==UiEvent.Type.POINTER_DOWN)store.dispatch(ServerToolsUiAction.focus(field));else if(event.getType()==UiEvent.Type.TEXT_INPUT&&!Character.isISOControl(event.getTypedChar()))store.dispatch(ServerToolsUiAction.input(field,event.getTypedChar()));else if(event.getType()==UiEvent.Type.KEY_DOWN&&(event.getKeyCode()==UiKeyCode.BACKSPACE||event.getKeyCode()==UiKeyCode.DELETE))store.dispatch(ServerToolsUiAction.backspace(field));return InputResult.CONSUMED;}}).build();}
    private static UiElement button(String key,String text,boolean enabled,Runnable action){return UiElement.type("Button").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.ENABLED,enabled).prop(StandardWidgets.ACTION,handler(action)).build();}
    private Runnable confirm(final ServerToolsUiState.Confirmation value){return new Runnable(){public void run(){store.dispatch(ServerToolsUiAction.confirm(value));}};}
    private static UiActionHandler handler(final Runnable action){return new UiActionHandler(){public InputResult handle(UiEvent event){action.run();return InputResult.CONSUMED;}};}
    private static UiElement label(String key,String text,String role,int lines,boolean bold,String tone){return UiElement.type("Label").key(key).prop(StandardWidgets.TEXT,text).prop(StandardWidgets.TEXT_ROLE,role).prop(StandardWidgets.MAX_LINES,lines).prop(StandardWidgets.BOLD,bold).prop(StandardWidgets.TONE,tone).build();}
    private TerminalServerToolsSectionModel tools(){TerminalHomeScreenModel.PageSnapshotModel page=model.getPageSnapshot("server_tools");return page.hasServerToolsSectionModel()?page.getServerToolsSectionModel():TerminalServerToolsSectionModel.placeholder();}
}
