package com.jsirgalaxybase.quest.core;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.util.*;
import org.junit.Test;

public class QuestChapterManagementServiceTest {
    private final QuestEditorActor actor=new QuestEditorActor(UUID.randomUUID(),"operator");

    @Test public void createsEditsAndPublishesWithPublishedQuestPlacements(){Chapters chapters=new Chapters();Quests quests=new Quests();UUID quest=UUID.randomUUID();quests.published.add(quest);QuestChapterManagementService service=service(chapters,quests,true);QuestChapterManagementResult created=service.create(actor,"工业时代");QuestChapterEditRequest edit=new QuestChapterEditRequest(created.getChapter().getDefinition().getId(),1,created.getChapter().getContentHash(),Arrays.asList(QuestChapterEditOperation.description("章节说明"),QuestChapterEditOperation.visibility(QuestVisibility.UNLOCKED),QuestChapterEditOperation.place(quest,10,20,2,2),QuestChapterEditOperation.move(quest,12,24),QuestChapterEditOperation.resize(quest,3,4)));QuestChapterManagementResult changed=service.apply(actor,edit);assertTrue(changed.isSuccess());QuestChapterEntry placement=changed.getChapter().getDefinition().getEntries().get(0);assertEquals(12,placement.getX());assertEquals(24,placement.getY());assertEquals(3,placement.getWidth());assertTrue(service.publish(actor,placement==null?null:changed.getChapter().getDefinition().getId(),1,changed.getChapter().getContentHash(),10L).isSuccess());}

    @Test public void rejectsUnauthorizedAndRollsBackInvalidBatch(){Chapters chapters=new Chapters();QuestChapterManagementService denied=service(chapters,new Quests(),false);assertEquals(QuestChapterManagementResult.Status.FORBIDDEN,denied.create(actor,"Denied").getStatus());QuestChapterManagementService service=service(chapters,new Quests(),true);QuestChapterManagementResult created=service.create(actor,"Chapter");int before=chapters.mutations;QuestChapterManagementResult result=service.apply(actor,new QuestChapterEditRequest(created.getChapter().getDefinition().getId(),1,created.getChapter().getContentHash(),Arrays.asList(QuestChapterEditOperation.description("not persisted"),QuestChapterEditOperation.move(UUID.randomUUID(),1,1))));assertEquals(QuestChapterManagementResult.Status.INVALID,result.getStatus());assertEquals(before,chapters.mutations);assertEquals("",chapters.value.getDefinition().getDescription());}

    @Test public void refusesPublishingChapterWithUnpublishedQuest(){Chapters chapters=new Chapters();QuestChapterManagementService service=service(chapters,new Quests(),true);QuestChapterManagementResult created=service.create(actor,"Chapter");UUID missing=UUID.randomUUID();QuestChapterManagementResult changed=service.apply(actor,new QuestChapterEditRequest(created.getChapter().getDefinition().getId(),1,created.getChapter().getContentHash(),Collections.singletonList(QuestChapterEditOperation.place(missing,0,0,1,1))));assertEquals(QuestChapterManagementResult.Status.INVALID,service.publish(actor,changed.getChapter().getDefinition().getId(),1,changed.getChapter().getContentHash(),1L).getStatus());}

    private static QuestChapterManagementService service(Chapters chapters,Quests quests,final boolean allowed){return new QuestChapterManagementService(chapters,quests,new QuestTransaction(){public <T>T inTransaction(Work<T> work){return work.execute();}},new QuestEditorAuthorization(){public boolean canManageDefinitions(QuestEditorActor ignored){return allowed;}});}
    private static final class Chapters implements QuestChapterRepository{StoredQuestChapter value;int mutations;public StoredQuestChapter createDraft(QuestChapterDefinition definition){mutations++;value=new StoredQuestChapter(definition,QuestDefinitionLifecycle.DRAFT,"h"+mutations,0);return value;}public StoredQuestChapter updateDraft(QuestChapterDefinition definition,String hash){mutations++;if(value==null||!value.getContentHash().equals(hash))throw new QuestDefinitionConflictException("stale");value=new StoredQuestChapter(definition,QuestDefinitionLifecycle.DRAFT,"h"+mutations,0);return value;}public boolean publish(UUID id,int version,String hash,long at){mutations++;if(value==null||!value.getContentHash().equals(hash))return false;value=new StoredQuestChapter(value.getDefinition(),QuestDefinitionLifecycle.PUBLISHED,hash,at);return true;}public boolean retire(UUID id,int version){return false;}public Optional<StoredQuestChapter> find(UUID id,int version){return value!=null&&value.getDefinition().getId().equals(id)&&value.getDefinition().getVersion()==version?Optional.of(value):Optional.<StoredQuestChapter>empty();}public Optional<StoredQuestChapter> findPublished(UUID id){return value!=null&&value.getLifecycle()==QuestDefinitionLifecycle.PUBLISHED&&value.getDefinition().getId().equals(id)?Optional.of(value):Optional.<StoredQuestChapter>empty();}public List<StoredQuestChapter> findAllPublished(){return Collections.emptyList();}}
    private static final class Quests implements QuestDefinitionRepository{final Set<UUID> published=new HashSet<UUID>();public Optional<StoredQuestDefinition> findPublished(UUID id){return published.contains(id)?Optional.of(new StoredQuestDefinition(new QuestDefinition(id,1,"Quest","",QuestLogic.AND,QuestLogic.AND,Collections.<UUID>emptySet(),Collections.<TaskDefinition>emptyList(),Collections.<RewardDefinition>emptyList()),QuestDefinitionLifecycle.PUBLISHED,"hash",0)):Optional.<StoredQuestDefinition>empty();}public StoredQuestDefinition createDraft(QuestDefinition value){throw new UnsupportedOperationException();}public StoredQuestDefinition updateDraft(QuestDefinition value,String hash){throw new UnsupportedOperationException();}public boolean publish(UUID id,int version,String hash,long at){return false;}public boolean retire(UUID id,int version){return false;}public Optional<StoredQuestDefinition> find(UUID id,int version){return Optional.empty();}public List<StoredQuestDefinition> findAllPublished(){return Collections.emptyList();}}
}
